const SUPABASE_URL="https://cjayajcjmpjjczwueyur.supabase.co";
const SUPABASE_KEY="sb_publishable_gID5KWmnvlNS3acHBkyETg_W6ACSKdB";
const extraStyle=document.createElement("link");extraStyle.rel="stylesheet";extraStyle.href="./style-extra.css?v=20260823-7";document.head.appendChild(extraStyle);
const chartStyle=document.createElement("link");chartStyle.rel="stylesheet";chartStyle.href="./style-charts.css?v=20260823-3";document.head.appendChild(chartStyle);
const modularStyle=document.createElement("link");modularStyle.rel="stylesheet";modularStyle.href="./style-modular.css?v=20260824-6";document.head.appendChild(modularStyle);
const upgradeStyle=document.createElement("link");upgradeStyle.rel="stylesheet";upgradeStyle.href="./style-upgrade.css?v=20260824-4";document.head.appendChild(upgradeStyle);
const $=s=>document.querySelector(s),urlKey=new URLSearchParams(location.search).get("key")||"";let key=localStorage.getItem("fitness-key")||"",nameCustomized=Boolean(localStorage.getItem("fitness-name")),userName=localStorage.getItem("fitness-name")||"朋友";
let allRows=[];if(urlKey)history.replaceState({},document.title,location.pathname+location.hash);const today=()=>new Date().toLocaleDateString("en-CA");$("#date").value=today();
function configureModularForm(){const view=$("#formView");if(!view)return;view.innerHTML=`<section class="daily-progress"><div><p class="kicker">TODAY'S CHECK-IN</p><h2>今天记录进度</h2><small id="progressText">0/5 项已记录</small></div><div class="progress-ring"><b id="progressNumber">0%</b></div></section><div id="moduleStrip" class="module-strip"><button type="button" data-jump="morning">晨间</button><button type="button" data-jump="pretrain">训练前</button><button type="button" data-jump="training">训练后</button><button type="button" data-jump="food">饮食</button><button type="button" data-jump="evening">晚间</button></div>
<section class="card orange-card record-module" data-module="morning"><h2><span class="num">01</span>晨间恢复</h2><p class="module-time">建议起床后记录 · 单独保存</p><div class="grid two"><label>日期<input id="date" name="logDate" type="date" required></label><label>睡眠（小时）<input name="sleepHours" type="number" step="0.1" min="0" max="16"></label></div><div class="grid three"><label>夜醒 / 夜尿<input name="wakeCount" type="number" min="0" max="30"></label><label>晨间精力 1–5<input name="energy" type="number" min="1" max="5"></label><label>静息心率<input name="restingHr" type="number" min="30" max="150"></label></div><div class="grid two"><label>睡眠评分<input name="sleepScore" type="number" min="0" max="100"></label><label>昨晚饮酒<select name="alcohol"><option value="否">否</option><option value="是">是</option></select></label></div><button class="module-save" type="button">保存晨间记录</button></section>
<section class="card lime-card record-module" data-module="pretrain"><h2><span class="num">02</span>训练前准备度</h2><p class="module-time">训练前 30–60 分钟记录 · 决定是否降量</p><div class="grid two"><label>计划训练<select name="sessionType"><option>上肢 A</option><option>下肢 A</option><option>恢复快走</option><option>上肢 B</option><option>下肢 B</option><option>耐力快走</option><option>恢复 / 休息</option></select></label><label>训练意愿 1–5<input name="motivation" type="number" min="1" max="5"></label></div><div class="grid three readiness-grid"><label>眼部状态<select name="eyeStatus"><option value="正常">正常</option><option value="轻微不适">轻微不适</option><option value="视力变化或眼痛">视力变化或眼痛</option></select></label><label>身体酸痛 0–5<input name="soreness" type="number" min="0" max="5" placeholder="0＝没有"></label><label>压力 0–5<input name="stress" type="number" min="0" max="5" placeholder="0＝没有"></label></div><label>训练前异常<textarea name="preSymptoms" rows="2" placeholder="无；或胸闷、头晕、异常心悸、眼部不适等"></textarea></label><div id="readinessHint" class="readiness-hint">填写睡眠、精力和眼部状态后，自动判断今天训练强度。</div><button class="module-save" type="button">保存训练前状态</button></section>
<section class="card pink-card record-module" data-module="training"><h2><span class="num">03</span>训练后表现</h2><p class="module-time">训练结束后记录 · 评价训练量与安全性</p><div class="grid three"><label>时长（分钟）<input name="duration" type="number" min="0" max="360"></label><label>平均心率<input name="avgHr" type="number" min="30" max="200"></label><label>最高心率<input name="maxHr" type="number" min="30" max="220"></label></div><div class="grid two"><label>计划完成度（%）<input name="completion" type="number" min="0" max="100"></label><label>主观强度 RPE 1–10<input name="rpe" type="number" min="1" max="10"></label></div><label>动作 × 重量 × 组数 × 次数 × RIR<textarea name="exercises" rows="8"></textarea></label><div id="exercisePlanHint" class="exercise-plan-hint"></div><button id="insertExerciseTemplate" class="ghost-btn full" type="button">填入本次动作模板</button><label>训练中或训练后异常<textarea name="postSymptoms" rows="2" placeholder="无；或疼痛、憋气、胸闷、头晕、眼部变化等"></textarea></label><div id="previousSessionHint" class="previous-hint">保存过同类型训练后，这里会显示上次表现。</div><button class="module-save" type="button">保存训练记录</button></section>
<section class="card blue-card record-module" data-module="food"><h2><span class="num">04</span>当天饮食</h2><p class="module-time">每餐后随时追加 · 食物照片不上传</p><label>餐次与主要食物<textarea name="meals" rows="5" placeholder="早餐 / 午餐 / 晚餐 / 加餐；标出蛋白质来源和大致份量"></textarea></label><div class="grid two"><label>估算总热量（kcal）<input name="estimatedCalories" type="number" min="0" max="10000" placeholder="例如 2200"></label><label class="upload local-food-photo"><input id="foodPhoto" type="file" accept="image/*" capture="environment"><b id="foodPhotoText">拍摄食物照片辅助估算</b><small>仅在本机临时预览，不上传、不保存</small></label></div><div id="foodPhotoPreview" class="food-photo-preview hidden"></div><label class="upload"><input id="files" type="file" accept="image/*" multiple><b id="fileText">选择训练 / 手表截图</b><small>最多6张；进一步压缩后保存，请勿选择食物照片</small></label><button class="module-save" type="button">保存饮食草稿</button></section>
<section class="card blue-card record-module" data-module="evening"><h2><span class="num">05</span>晚间与身体指标</h2><p class="module-time">睡前记录 · 检查延迟性不适</p><label>晚间不适与异常<textarea name="symptoms" rows="3" placeholder="没有写“无”；如有胸部、头晕、心悸、眼部或疼痛请具体记录"></textarea></label><div class="grid three"><label>当天步数<input name="steps" type="number" min="0" max="100000"></label><label>体重（kg）<input name="bodyWeight" type="number" step="0.1" min="25" max="300"></label><label>肚脐腰围（cm）<input name="waist" type="number" step="0.1" min="40" max="250"></label></div><label>补充备注<textarea name="notes" rows="3"></textarea></label><button class="module-save" type="button">保存晚间记录</button></section><section class="finalize-card"><div><b>当日汇总</b><p>各模块可分时保存；最后合并为当天一条记录并生成完整日报。</p></div><button id="save" class="submit">合并保存并生成日报</button></section>`;$("#date").value=today()}
configureModularForm();
const mealTypes=[{id:"breakfast",label:"早餐",icon:"☀️"},{id:"lunch",label:"午餐",icon:"🥗"},{id:"dinner",label:"晚餐",icon:"🌙"},{id:"snack",label:"加餐",icon:"🍎"}];
let mealResults={};
function mealResultsKey(){return`fitness-meals-${key.slice(0,12)||"guest"}-${$("#date")?.value||today()}`}
function loadMealResults(){try{mealResults=JSON.parse(localStorage.getItem(mealResultsKey())||"{}")||{}}catch{mealResults={}}renderMealSummary()}
function saveMealResults(){localStorage.setItem(mealResultsKey(),JSON.stringify(mealResults));renderMealSummary();saveDraft()}
function configureMealAnalyzer(){const card=document.querySelector('[data-module="food"]');if(!card)return;card.innerHTML=`<h2><span class="num">04</span>三餐营养识别</h2><p class="module-time">支持照片、文字、照片＋文字三种方式 · 每餐确认后计入全天</p><div class="meal-list">${mealTypes.map(m=>`<article class="meal-card" data-meal="${m.id}"><div class="meal-head"><b>${m.icon} ${m.label}</b><span id="${m.id}Status">未记录</span></div><label>文字描述（可单独估算，也可辅助照片）<input id="${m.id}Context" placeholder="例如：米饭半碗、鸡胸约一掌大、炒菜约一盘"></label><label class="upload meal-photo"><input id="${m.id}Photo" type="file" accept="image/*" capture="environment"><b>拍照识别 ${m.label}</b><small>可只拍照、只写文字或两者一起；照片分析后立即丢弃</small></label><div id="${m.id}Preview" class="food-photo-preview hidden"></div><div class="meal-actions"><button class="small-btn analyze-meal" type="button" data-analyze="${m.id}">智能估算热量</button><button class="ghost-btn" type="button" data-manual="${m.id}">手动校正</button></div><div id="${m.id}Result" class="meal-result hidden"></div></article>`).join("")}</div><section id="mealSummary" class="meal-summary"></section><input name="meals" id="mealsText" type="hidden"><input name="mealsJson" id="mealsJson" type="hidden"><input name="estimatedCalories" id="estimatedCalories" type="hidden"><input name="proteinGrams" id="proteinGrams" type="hidden"><input id="foodPhoto" type="file" class="hidden" tabindex="-1"><span id="foodPhotoText" class="hidden"></span><div id="foodPhotoPreview" class="hidden"></div><label class="upload"><input id="files" type="file" accept="image/*" multiple><b id="fileText">选择训练 / 手表截图</b><small>最多6张；压缩后保存，请勿选择食物照片</small></label><button class="module-save" type="button">保存饮食草稿</button>`;mealTypes.forEach(m=>{$(`#${m.id}Photo`).onchange=e=>previewMealPhoto(m.id,e.target.files?.[0]);$(`[data-analyze="${m.id}"]`).onclick=()=>analyzeMeal(m.id);$(`[data-manual="${m.id}"]`).onclick=()=>manualMeal(m.id)});loadMealResults()}
function manualMeal(id){mealResults[id]={items:[],estimated_calories:0,protein_g:0,carbs_g:0,fat_g:0,confidence:"low",assumptions:"手动校正，请依据包装营养表、称重结果或实际份量填写。",confirmed:false,photo_stored:false};const box=$(`#${id}Result`);box.innerHTML=mealResultEditor(id,mealResults[id]);box.classList.remove("hidden");bindMealEditor(id);$(`#${id}Status`).textContent="待确认";box.querySelector('[data-meal-field="items"]')?.focus()}
function previewMealPhoto(id,file){const box=$(`#${id}Preview`);if(!file){box.classList.add("hidden");box.innerHTML="";return}const url=URL.createObjectURL(file);box.innerHTML=`<img src="${url}" alt="${id}食物照片"><div><b>待识别</b><small>识别完成或离开页面后，此照片不会进入训练档案。</small></div>`;box.classList.remove("hidden");box.querySelector("img").onload=()=>URL.revokeObjectURL(url)}
function mealResultEditor(id,result){const items=(result.items||[]).map(x=>x.name+(x.portion?`（${x.portion}）`:"")).join("、");return `<div class="meal-confidence ${esc(result.confidence||"low")}">${result.confidence==="high"?"较高":result.confidence==="medium"?"中等":"较低"}置信度 · 建议核对份量</div><label>识别食物<input data-meal-field="items" value="${esc(items)}"></label><div class="grid two"><label>热量 kcal<input data-meal-field="calories" type="number" min="0" max="5000" value="${Number(result.estimated_calories)||0}"></label><label>蛋白质 g<input data-meal-field="protein" type="number" min="0" max="500" step="0.1" value="${Number(result.protein_g)||0}"></label></div><div class="grid two"><label>碳水 g<input data-meal-field="carbs" type="number" min="0" max="1000" step="0.1" value="${Number(result.carbs_g)||0}"></label><label>脂肪 g<input data-meal-field="fat" type="number" min="0" max="500" step="0.1" value="${Number(result.fat_g)||0}"></label></div><small>${esc(result.assumptions||"图片估算存在误差，请按实际份量修改。")}</small><button class="ghost-btn confirm-meal" type="button">确认并计入全天</button>`}
function bindMealEditor(id){const box=$(`#${id}Result`);box.querySelector(".confirm-meal")?.addEventListener("click",()=>{const get=f=>Number(box.querySelector(`[data-meal-field="${f}"]`)?.value)||0;mealResults[id]={...mealResults[id],items_text:box.querySelector('[data-meal-field="items"]')?.value||"",estimated_calories:get("calories"),protein_g:get("protein"),carbs_g:get("carbs"),fat_g:get("fat"),confirmed:true,photo_stored:false};saveMealResults();flashButton(box.querySelector(".confirm-meal"),"✓ 已计入全天");note(`${mealTypes.find(x=>x.id===id)?.label}已确认，照片未保存`)})}
async function analyzeMeal(id){const file=$(`#${id}Photo`)?.files?.[0],btn=$(`[data-analyze="${id}"]`),context=$(`#${id}Context`)?.value.trim()||"";if(!file&&!context)return flashButton(btn,"请拍照或写描述","error");btn.disabled=true;flashButton(btn,"正在识别…","busy",10000);try{const image=file?await compressMealForAnalysis(file):"";const response=await fetch(`${SUPABASE_URL}/functions/v1/analyze-meal`,{method:"POST",headers:{"Content-Type":"application/json","apikey":SUPABASE_KEY,"Authorization":`Bearer ${SUPABASE_KEY}`},body:JSON.stringify({image,meal_type:id,context})});const result=await response.json();if(!response.ok)throw Error(result.error||`识别失败（${response.status}）`);mealResults[id]={...result,confirmed:false,photo_stored:false};const box=$(`#${id}Result`);box.innerHTML=mealResultEditor(id,result);box.classList.remove("hidden");bindMealEditor(id);$(`#${id}Status`).textContent="待确认";flashButton(btn,"✓ 识别完成");note("识别结果是估算值，请核对份量后点击确认") }catch(error){flashButton(btn,"识别失败 · 重试","error",3500);note(error.message.includes("尚未配置")?error.message:`食物识别失败：${error.message}`)}finally{btn.disabled=false}}
async function compressMealForAnalysis(file){if(!file.type.startsWith("image/"))throw Error("请选择食物照片");const bitmap=await createImageBitmap(file),max=1280,scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement("canvas");canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext("2d").drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close?.();return canvas.toDataURL("image/jpeg",.72)}
function renderMealSummary(){if(!$("#mealSummary"))return;const confirmed=Object.entries(mealResults).filter(([,v])=>v?.confirmed),calories=Math.round(confirmed.reduce((s,[,v])=>s+(Number(v.estimated_calories)||0),0)),protein=Math.round(confirmed.reduce((s,[,v])=>s+(Number(v.protein_g)||0),0)*10)/10;mealTypes.forEach(m=>{const result=mealResults[m.id],box=$(`#${m.id}Result`);if(!result&&box){box.innerHTML="";box.classList.add("hidden")}if(result&&box&&!box.innerHTML){box.innerHTML=mealResultEditor(m.id,result);box.classList.remove("hidden");bindMealEditor(m.id)}if($(`#${m.id}Status`))$(`#${m.id}Status`).textContent=result?.confirmed?`${Math.round(result.estimated_calories||0)} kcal`:result?"待确认":"未记录"});$("#mealSummary").innerHTML=`<div><small>已确认餐次</small><b>${confirmed.length} / 4</b></div><div><small>全天摄入</small><b>${calories} kcal</b></div><div><small>蛋白质</small><b>${protein} g</b></div><p>仅保存确认后的营养结果；食物照片不进入档案。</p>`;$("#mealsJson").value=JSON.stringify(mealResults);$("#estimatedCalories").value=calories||"";$("#proteinGrams").value=protein||"";$("#mealsText").value=confirmed.map(([id,v])=>`${mealTypes.find(x=>x.id===id)?.label}：${v.items_text||(v.items||[]).map(x=>x.name).join("、")}（约${Math.round(v.estimated_calories||0)} kcal，蛋白质${Number(v.protein_g||0)}g）`).join("\n")}
configureMealAnalyzer();
const eveningGrid=document.querySelector('[data-module="evening"] .grid');if(eveningGrid)eveningGrid.insertAdjacentHTML("beforeend",'<label>手表活动消耗（kcal）<input name="activeCalories" type="number" min="0" max="6000" placeholder="优先填此项"></label><label>本次训练消耗（kcal）<input name="trainingCalories" type="number" min="0" max="4000" placeholder="手表有则填写"></label>');
["bmrCalories","totalExpenditure","calorieBalance","proteinTargetMin","proteinTargetMax"].forEach(name=>{const input=document.createElement("input");input.type="hidden";input.name=name;$("#logForm").appendChild(input)});
function energyMetrics(p={}){const profile=profileFor(p),year=new Date().getFullYear(),age=profile.birthYear?year-Number(profile.birthYear):null,weight=Number(p.bodyWeight||profile.weight||0),height=Number(profile.height||0),sex=profile.sex||"male",intake=Number(p.estimatedCalories||0),protein=Number(p.proteinGrams||0),duration=Number(p.duration||0),steps=Number(p.steps||0),watchActive=Number(p.activeCalories||0),enteredTraining=Number(p.trainingCalories||0);if(!age||!weight||!height)return{complete:false,intake,protein};const sexOffset=sex==="female"?-161:sex==="male"?5:-78,bmr=Math.round(10*weight+6.25*height-5*age+sexOffset),met=/快走/.test(p.sessionType||"")?3.8:/恢复|休息/.test(p.sessionType||"")?2.3:4.5,estimatedTraining=duration?Math.round(met*3.5*weight/200*duration):0,training=enteredTraining||estimatedTraining,stepExtra=Math.max(0,steps-3000)*weight*.00042,expenditure=Math.round(watchActive?bmr*1.2+watchActive:bmr*1.2+training+stepExtra),balance=intake?Math.round(intake-expenditure):null;return{complete:true,bmr,expenditure,balance,intake,protein,training,source:watchActive?"手表活动消耗":"公式估算",proteinMin:Math.round(weight*1.4),proteinMax:Math.round(weight*2)}}
function syncEnergyFields(){renderMealSummary();const raw=Object.fromEntries(new FormData($("#logForm")).entries()),m=energyMetrics(raw);if(!m.complete)return;$("[name=bmrCalories]").value=m.bmr;$("[name=totalExpenditure]").value=m.expenditure;$("[name=calorieBalance]").value=m.balance??"";$("[name=proteinTargetMin]").value=m.proteinMin;$("[name=proteinTargetMax]").value=m.proteinMax;const summary=$("#mealSummary");if(summary)summary.insertAdjacentHTML("beforeend",`<div class="energy-balance ${m.balance!=null&&Math.abs(m.balance)>700?"warn":""}"><small>估算总消耗（${m.source}）</small><b>${m.expenditure} kcal</b><span>${m.balance==null?"确认餐次后显示热量差":`当日热量差 ${m.balance>0?"+":""}${m.balance} kcal`}</span></div><div class="protein-target"><small>蛋白质参考</small><b>${m.protein||0} / ${m.proteinMin}–${m.proteinMax} g</b></div>`)}
$("#logForm").addEventListener("input",e=>{if(["activeCalories","trainingCalories","steps","duration","bodyWeight"].includes(e.target.name))syncEnergyFields()});
$("#logForm").addEventListener("submit",syncEnergyFields,{capture:true});
function syncAccountUI(){const bound=Boolean(key);$("#accountButton").textContent=bound?"● 已免登录绑定":"○ 恢复账户";$("#accountButton").classList.toggle("unbound",!bound);$("#boundAccount").classList.toggle("hidden",!bound);$("#restoreAccount").classList.toggle("hidden",bound);if(!bound)$("#accountModal").classList.remove("hidden")}
$("#accountButton").onclick=()=>{$("#accountModal").classList.remove("hidden");syncAccountUI()};$("#closeAccount").onclick=()=>$("#accountModal").classList.add("hidden");
const switchBtn=document.createElement("button");switchBtn.id="switchAccount";switchBtn.type="button";switchBtn.className="ghost-btn full";switchBtn.textContent="恢复另一个账户";$("#copyRecovery").after(switchBtn);switchBtn.onclick=()=>{$("#boundAccount").classList.add("hidden");$("#restoreAccount").classList.remove("hidden");$("#recoveryInput").focus()};
function newAccountKey(){const bytes=new Uint8Array(32);crypto.getRandomValues(bytes);return btoa(String.fromCharCode(...bytes)).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
$("#createAccount").onclick=async()=>{const name=$("#newNicknameInput").value.trim().slice(0,16);if(!name)return note("请先填写希望教练称呼你的名字");key=newAccountKey();userName=name;nameCustomized=true;localStorage.setItem("fitness-key",key);localStorage.setItem("fitness-name",userName);allRows=[];$("#nicknameInput").value=userName;$("#coachTitle").textContent=`我的训练计划`;syncAccountUI();$("#accountModal").classList.add("hidden");note("独立账户已创建。你的记录与其他用户完全分开。");await ensureRows(true)};
$("#copyRecovery").onclick=async()=>{try{await navigator.clipboard.writeText(key);note("恢复码已复制，请只保存到你自己的备忘录中")}catch{prompt("请复制并妥善保存恢复码",key)}};
$("#restoreButton").onclick=async()=>{const value=$("#recoveryInput").value.trim();if(!/^[A-Za-z0-9_-]{20,}$/.test(value))return note("恢复码格式不正确");try{await rpc("list_fitness_logs",{p_key:value});key=value;localStorage.setItem("fitness-key",key);allRows=[];syncAccountUI();$("#accountModal").classList.add("hidden");note("账户恢复成功，此微信以后将自动进入");await ensureRows(true)}catch{note("恢复码无效，请检查后重试")}};
syncAccountUI();
if($("#nicknameInput")){$("#nicknameInput").value=userName;$("#coachTitle").textContent=`我的训练计划`;$("#saveNickname").onclick=()=>{const value=$("#nicknameInput").value.trim().slice(0,16);if(!value)return note("请填写希望教练称呼你的名字");userName=value;nameCustomized=true;localStorage.setItem("fitness-name",userName);$("#coachTitle").textContent=`我的训练计划`;note(`以后反馈会称呼你“${userName}”`)}}
const draftKey="fitness-log-draft";function saveDraft(){const data=Object.fromEntries(new FormData($("#logForm")).entries());localStorage.setItem(draftKey,JSON.stringify(data))}function restoreDraft(){try{const data=JSON.parse(localStorage.getItem(draftKey)||"{}");Object.entries(data).forEach(([name,value])=>{const el=$(`[name="${name}"]`);if(el&&value!=="")el.value=value})}catch{localStorage.removeItem(draftKey)}}$("#logForm").addEventListener("input",saveDraft);restoreDraft();
const moduleNames={morning:"晨间",pretrain:"训练前",training:"训练后",food:"饮食",evening:"晚间"};function moduleStateKey(){return`fitness-modules-${key.slice(0,8)||"guest"}-${$("#date")?.value||today()}`}function completedModules(){try{return JSON.parse(localStorage.getItem(moduleStateKey())||"[]")}catch{return[]}}function renderModuleProgress(){const done=completedModules(),pct=done.length*20;$("#progressText").textContent=`${done.length}/5 项已记录${done.length<5?` · 待完成：${Object.keys(moduleNames).filter(x=>!done.includes(x)).map(x=>moduleNames[x]).join("、")}`:" · 可以生成完整日报"}`;$("#progressNumber").textContent=`${pct}%`;document.querySelectorAll(".record-module").forEach(card=>{const ok=done.includes(card.dataset.module);card.classList.toggle("module-done",ok);const btn=card.querySelector(".module-save");if(btn)btn.textContent=ok?`✓ ${moduleNames[card.dataset.module]}已保存`:`保存${moduleNames[card.dataset.module]}记录`});document.querySelectorAll("[data-jump]").forEach(btn=>btn.classList.toggle("done",done.includes(btn.dataset.jump)))}function saveModule(card){saveDraft();const done=new Set(completedModules());done.add(card.dataset.module);localStorage.setItem(moduleStateKey(),JSON.stringify([...done]));renderModuleProgress();note(`${moduleNames[card.dataset.module]}记录已保存在本机，可稍后继续补充`)}document.querySelectorAll(".module-save").forEach(btn=>btn.onclick=()=>saveModule(btn.closest(".record-module")));document.querySelectorAll("[data-jump]").forEach(btn=>btn.onclick=()=>document.querySelector(`[data-module="${btn.dataset.jump}"]`)?.scrollIntoView({behavior:"smooth",block:"start"}));$("#date").addEventListener("change",renderModuleProgress);renderModuleProgress();
$("#mascot").className="mascot tiger cycle-day-1 stage-0";$("#mascot").style.backgroundPosition="0 0";const moodBadge=document.createElement("span");moodBadge.id="mascotMood";moodBadge.className="mascot-mood";moodBadge.textContent="💛 虎虎陪你，今天也算数";$(".mascot-copy")?.appendChild(moodBadge);
document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=async()=>{document.querySelectorAll("[data-tab]").forEach(x=>x.classList.remove("active"));b.classList.add("active");["form","history","coach"].forEach(t=>$("#"+t+"View").classList.toggle("hidden",b.dataset.tab!==t));if(b.dataset.tab!=="form")await ensureRows();if(b.dataset.tab==="history")renderHistory(allRows);if(b.dataset.tab==="coach")renderCoach(allRows)});
const note=t=>{$("#notice").textContent=t;$("#notice").classList.remove("hidden");scrollTo({top:0,behavior:"smooth"})};
$("#files").onchange=e=>$("#fileText").textContent=`已选择 ${Math.min(e.target.files.length,6)} 张训练/手表截图`;
let foodPreviewUrl="";$("#foodPhoto").onchange=e=>{if(foodPreviewUrl)URL.revokeObjectURL(foodPreviewUrl);const file=e.target.files?.[0],preview=$("#foodPhotoPreview");if(!file){preview.classList.add("hidden");preview.innerHTML="";return}foodPreviewUrl=URL.createObjectURL(file);preview.innerHTML=`<img src="${foodPreviewUrl}" alt="食物照片本机预览"><div><b>照片不会上传</b><small>请根据食物和份量填写上方估算热量；保存后照片立即丢弃。</small></div>`;preview.classList.remove("hidden");$("#foodPhotoText").textContent="已拍摄 · 仅本机预览"};
async function rpc(name,body){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:"POST",headers:{"Content-Type":"application/json","apikey":SUPABASE_KEY},body:JSON.stringify(body)});const text=await r.text();let out=null;try{out=text?JSON.parse(text):null}catch{out=text}if(!r.ok)throw Error(out?.message||out?.error||`请求失败（${r.status}）`);return out}
async function compress(file){if(!file.type.startsWith("image/"))throw Error(`${file.name} 不是图片`);const bitmap=await createImageBitmap(file),max=960,scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement("canvas");canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext("2d").drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close?.();let quality=.62,data=canvas.toDataURL("image/jpeg",quality);while(data.length>180000&&quality>.32){quality-=.07;data=canvas.toDataURL("image/jpeg",quality)}if(data.length>240000)throw Error(`${file.name} 压缩后仍过大，请裁剪后上传`);return{name:file.name,mime_type:"image/jpeg",data}}
$("#logForm").onsubmit=async e=>{e.preventDefault();if(!key)return note("请先创建或恢复专属账户");const btn=$("#save");btn.disabled=true;try{const f=new FormData(e.target),files=[...$("#files").files].slice(0,6),images=[],data=Object.fromEntries(f.entries()),savedStateKey=moduleStateKey(),savedMealKey=mealResultsKey();data.profileName=userName;data.completedModules=completedModules();data.recordCompleteness=data.completedModules.length*20;data.foodPhotoStored=false;data.symptoms=[data.preSymptoms,data.postSymptoms,data.symptoms].filter(x=>x&&String(x).trim()&&!/^(无|没有|正常|暂无)$/.test(String(x).trim())).join("；")||"无";["sleepHours","wakeCount","energy","restingHr","duration","avgHr","maxHr","completion","soreness","stress","steps","sleepScore","bodyWeight","waist","motivation","rpe","estimatedCalories","proteinGrams","activeCalories","trainingCalories","bmrCalories","totalExpenditure","calorieBalance","proteinTargetMin","proteinTargetMax"].forEach(n=>{if(n in data)data[n]=data[n]===""?null:Number(data[n])});const invalid=validateEntry(data);if(invalid)throw Error(invalid);note("正在合并当天记录、压缩训练/手表截图并生成日报…");for(const file of files)images.push(await compress(file));await rpc("save_fitness_log",{p_key:key,p_payload:data,p_images:images});allRows=[];e.target.reset();if(foodPreviewUrl)URL.revokeObjectURL(foodPreviewUrl);foodPreviewUrl="";$("#foodPhotoPreview").classList.add("hidden");$("#foodPhotoPreview").innerHTML="";$("#foodPhotoText").textContent="拍摄食物照片辅助估算";localStorage.removeItem(draftKey);localStorage.removeItem(savedStateKey);localStorage.removeItem(savedMealKey);mealResults={};$("#date").value=today();$("#fileText").textContent="选择训练 / 手表截图";renderMealSummary();renderModuleProgress();updateExercisePlanHint();note(`当天记录已合并保存（完整度 ${data.recordCompleteness}%），日报已经生成。`);showFeedback(data);await ensureRows(true)}catch(err){note(`${err.message||"保存失败"}。草稿仍保存在本机，可修改后重试。`)}finally{btn.disabled=false}};
function validateEntry(p){const ranges={sleepHours:[0,16,"睡眠时长"],wakeCount:[0,30,"夜醒次数"],energy:[1,5,"精力"],restingHr:[30,150,"静息心率"],motivation:[1,5,"训练意愿"],duration:[0,360,"训练时长"],avgHr:[30,200,"平均心率"],maxHr:[30,220,"最高心率"],completion:[0,100,"完成度"],rpe:[1,10,"主观强度"],soreness:[0,5,"酸痛"],stress:[0,5,"压力"],steps:[0,100000,"步数"],sleepScore:[0,100,"睡眠评分"],bodyWeight:[25,300,"体重"],waist:[40,250,"腰围"],estimatedCalories:[0,10000,"估算热量"]};for(const[k,[min,max,label]]of Object.entries(ranges)){if(p[k]!==null&&p[k]!==undefined&&p[k]!==""&&(!Number.isFinite(Number(p[k]))||Number(p[k])<min||Number(p[k])>max))return`${label}应填写 ${min}–${max} 之间的数值`}if(p.avgHr&&p.maxHr&&p.maxHr<p.avgHr)return"最高心率不能低于平均心率";return""}
async function ensureRows(force=false){if(!key){note("请使用专属链接进入");return[]}if(allRows.length&&!force)return allRows;try{allRows=await rpc("list_fitness_logs",{p_key:key});if(!nameCustomized){const remoteName=allRows.map(row=>row.payload?.profileName).find(Boolean);if(remoteName){userName=String(remoteName).trim().slice(0,16)||userName;nameCustomized=true;localStorage.setItem("fitness-name",userName);if($("#nicknameInput"))$("#nicknameInput").value=userName;if($("#coachTitle"))$("#coachTitle").textContent=`我的训练计划`}}updateMascot(allRows);updatePreviousSessionHint();return allRows}catch(err){note(err.message||"读取失败");return[]}}
function updateReadiness(){const f=$("#logForm").elements,sleep=Number(f.sleepHours.value),energy=Number(f.energy.value),soreness=Number(f.soreness?.value),stress=Number(f.stress?.value),eye=f.eyeStatus?.value,hint=$("#readinessHint");if(!hint)return;let level="ready",text="状态信息还不完整，先如实填写再决定训练强度。";if(eye==="视力变化或眼痛"){level="stop";text="今天不训练：出现视力变化或眼痛，应停止运动并联系眼科。"}else if(eye==="轻微不适"){level="reduce";text="眼部有轻微不适：取消跑跳和震动，力量训练降量 30%，若加重立即停止。"}else if((sleep&&sleep<6)||(energy&&energy<=2)||(soreness&&soreness>=4)||(stress&&stress>=4)){level="reduce";text="今天恢复不足：总组数减少约 25%，保留 3–4 次余力；也可改成 20–30 分钟轻松快走。"}else if(sleep>=7&&energy>=3){text="今天可以按计划训练：全程不憋气、不震动，复合动作保留 3 次余力。"}hint.className=`readiness-hint ${level}`;hint.textContent=text}
function updatePreviousSessionHint(){const type=$("[name=sessionType]")?.value,hint=$("#previousSessionHint");if(!hint)return;const last=allRows.find(x=>x.payload?.sessionType===type&&x.payload?.exercises);if(!last){hint.textContent="保存过同类型训练后，这里会显示上次表现。";return}const p=last.payload;hint.innerHTML=`<b>上次 ${esc(type)} · ${esc(p.logDate||"")}</b><p>${esc(String(p.exercises).slice(0,220))}</p><small>${p.sleepHours<6.5||hasSymptom(p.symptoms)?"本次先维持或降量，不追求加重。":"动作稳定且全程不憋气时：优先每组增加 1 次，达到次数上限后再增加最小重量。"}</small>`}
const exercisePlans={"上肢 A":["器械推胸","高位下拉","上斜器械推胸","坐姿划船","器械肩推","侧平举","二头弯举","绳索下压"],"下肢 A":["腿举","坐姿腿弯举","罗马尼亚硬拉","提踵","死虫式"],"上肢 B":["上斜器械推胸","胸托划船","器械推胸","高位下拉","器械肩推","侧平举","二头弯举","三头下压"],"下肢 B":["腿屈伸","罗马尼亚硬拉","保加利亚分腿蹲","腿弯举","提踵","核心训练"],"恢复快走":["快走"],"耐力快走":["快走"],"恢复 / 休息":["轻松步行","活动度练习"]};function exerciseTemplate(type){return(exercisePlans[type]||[]).map(x=>`${x}｜重量：__｜组数：__｜次数：__｜RIR：__`).join("\n")}function updateExercisePlanHint(){const type=$("[name=sessionType]")?.value||"上肢 A",items=exercisePlans[type]||[],hint=$("#exercisePlanHint"),area=$("[name=exercises]");if(hint)hint.innerHTML=`<b>${esc(type)} 建议记录动作</b><div>${items.map(x=>`<span>${esc(x)}</span>`).join("")}</div>`;if(area)area.placeholder=exerciseTemplate(type);updatePreviousSessionHint()}function insertExerciseTemplate(){const area=$("[name=exercises]"),type=$("[name=sessionType]")?.value;if(!area)return;if(area.value.trim()&&!confirm("当前已有动作记录，是否用所选计划模板替换？"))return;area.value=exerciseTemplate(type);area.dispatchEvent(new Event("input",{bubbles:true}));area.focus()}[$("[name=sleepHours]"),$("[name=energy]"),$("[name=soreness]"),$("[name=stress]"),$("[name=eyeStatus]")].filter(Boolean).forEach(el=>el.addEventListener("input",updateReadiness));$("[name=sessionType]")?.addEventListener("change",updateExercisePlanHint);$("#insertExerciseTemplate")?.addEventListener("click",insertExerciseTemplate);updateReadiness();updateExercisePlanHint();
function renderHistory(rows){const dates=[...new Set(rows.map(x=>x.payload?.logDate).filter(Boolean))].sort().reverse();$("#historyCount").textContent=`${rows.length} 条`;$("#dateStrip").innerHTML=dates.slice(0,12).map((d,i)=>`<button data-date="${esc(d)}" class="date-chip${i===0?' selected':''}">${shortDate(d)}</button>`).join("");$("#dateStrip").querySelectorAll("[data-date]").forEach(b=>b.onclick=()=>{$("#historyDate").value=b.dataset.date;filterDate(b.dataset.date)});renderDailyFeedback(rows[0]?.payload||null);renderLogs(rows)}
function filterDate(date){document.querySelectorAll(".date-chip").forEach(b=>b.classList.toggle("selected",b.dataset.date===date));renderLogs(allRows.filter(x=>x.payload?.logDate===date),date)}
$("#showDate").onclick=e=>{e.preventDefault();const d=$("#historyDate").value;if(d)filterDate(d)};$("#showAll").onclick=e=>{e.preventDefault();$("#historyDate").value="";document.querySelectorAll(".date-chip").forEach(b=>b.classList.remove("selected"));renderLogs(allRows)};
function renderLogs(rows,date=""){$("#logs").innerHTML=rows.length?rows.map(logCard).join(""):`<div class="empty">${date?esc(date)+" 暂无记录":"还没有记录"}</div>`}
function logCard(x){const p=x.payload||{},imgs=x.images||[];return `<article class="log"><div class="log-top"><div><small>${esc(p.logDate||"")}</small><h3>${esc(p.sessionType||"日常反馈")}</h3></div><span class="status-dot">已记录</span></div><div class="stats"><span>睡眠<br><b>${p.sleepHours??"—"}h</b></span><span>时长<br><b>${p.duration??"—"}min</b></span><span>平均心率<br><b>${p.avgHr??"—"}</b></span><span>精力<br><b>${p.energy??"—"}/5</b></span></div>${block("训练",p.exercises)}${block("饮食",p.meals)}${block("身体反馈",p.symptoms)}${block("备注",p.notes)}${imgs.length?`<div class="gallery">${imgs.map(i=>`<a target="_blank" href="${i.data}"><img loading="lazy" src="${i.data}" alt="反馈截图"></a>`).join("")}</div>`:""}</article>`}
function feedbackFor(p){if(!p)return`${userName}，今天还没看到你的记录呢。别给自己太大压力，哪怕只记下睡眠和身体状态，也算把今天接住了。`;const name=userName,session=p.sessionType||"训练",opening=p.duration>0?`${name}，我刚认真看完你今天的记录。${p.duration} 分钟的${session}，你确实做下来了。`:`${name}，我看完了。今天虽然没有正式训练，但你愿意把真实状态留下来，这很重要。`;let praise="";if(p.completion>=85)praise=`完成度 ${p.completion}%，挺漂亮的。不是嘴上说想改变，是你真的在一点点往前拱。`;else if(p.completion>=60)praise=`完成度 ${p.completion}%，不用嫌它不够满。能稳定做下去，比偶尔拼一次狠的更值钱。`;else if(p.duration>0)praise="今天不用追求满分。先把动作做稳，把呼吸守住，这次训练就有价值。";let focus="";if(p.eyeStatus==="视力变化或眼痛")focus="但眼部状态是今天最重要的事。先停止训练，不要观察着硬练，尽快联系眼科。";else if(p.eyeStatus==="轻微不适")focus="你记录了眼部轻微不适。下一次先取消任何震动和冲击，总训练量减少三成；只要不适加重就立即停止。";else if(hasSymptom(p.symptoms))focus=`但我最在意的是你写的“${p.symptoms}”。下一次先降重量、减一到两组，别硬扛；如果是视力变化、眼痛、胸闷、头晕或异常心悸，就先停下来去看医生。`;else if(p.sleepHours&&p.sleepHours<6.5)focus=`不过你只睡了 ${p.sleepHours} 小时。今晚别想着靠多练补回来，真正该补的是睡眠。下一次训练保留三到四次余力，做完还有劲儿，才是对的。`;else if(p.wakeCount>=2)focus=`夜里醒了 ${p.wakeCount} 次，这说明身体恢复得不算完整。下一次别加训练量，动作之间多歇一会儿，下午也尽量早点结束。`;else if(p.maxHr>=150)focus=`最高心率到了 ${p.maxHr}。单看数字不一定有问题，但你要记得当时有没有胸闷、头晕或心慌；有任何不舒服，就不要继续顶。`;else focus="今天的数据里没看到明显的危险信号。继续记住三件事：不憋气，不震动，不练到力竭。动作慢一点，反而更适合你。";const close=p.duration>0?"好了，今天这次算数。去吃一顿有蛋白质的饭，晚上早点睡。明天不用证明什么，我们接着来。":"今天就先把恢复做好。喝水分次喝，晚上早点躺下。等身体准备好了，我们再稳稳地练。";return[opening,praise,focus,close].filter(Boolean).join("\n\n")}
let currentFeedback="";function renderDailyFeedback(p){currentFeedback=feedbackFor(p);$("#dailyFeedback").innerHTML=`<div class="voice-orb">♪</div><div><b>${p?esc(p.logDate||"最近一次")+" · "+esc(p.sessionType||"反馈"):"等待第一次记录"}</b><p>${esc(currentFeedback)}</p></div>`}
function showFeedback(p){currentFeedback=feedbackFor(p);$("#modalFeedback").textContent=currentFeedback;$("#feedbackModal").classList.remove("hidden");speakFeedback(currentFeedback)}
function availableChineseVoices(){return speechSynthesis.getVoices().filter(v=>/^zh/i.test(v.lang))}function chosenVoice(){const voices=availableChineseVoices(),saved=localStorage.getItem("fitness-voice");return voices.find(v=>v.name===saved)||voices.find(v=>/Xiaoxiao|Xiaoyi|Ting-Ting|Sinji|Meijia|female|女声|甜美|小艺/i.test(v.name))||voices.find(v=>/^zh-CN/i.test(v.lang))||voices[0]||null}function loadVoiceOptions(){if(!("speechSynthesis" in window))return;const select=$("#voiceSelect"),voices=availableChineseVoices();if(!select)return;const current=chosenVoice();select.innerHTML=voices.length?voices.map(v=>`<option value="${esc(v.name)}"${current?.name===v.name?' selected':''}>${esc(v.name.replace(/Microsoft|Google|Huawei/gi,'').trim()||'中文女声')}</option>`).join(""):'<option>手机默认女声</option>';select.onchange=()=>localStorage.setItem("fitness-voice",select.value)}
function systemSpeakFeedback(text){if(!("speechSynthesis" in window))return note("当前微信浏览器不支持语音播放，请阅读文字反馈");speechSynthesis.cancel();const female=chosenVoice(),parts=String(text).split(/\n{2,}|(?<=[。！？])\s*/).map(x=>x.trim()).filter(Boolean);let i=0;const play=()=>{if(i>=parts.length)return;const u=new SpeechSynthesisUtterance(parts[i]);u.voice=female;u.lang="zh-CN";u.rate=i===0?.86:.89;u.pitch=i===0?1.04:1.01;u.volume=1;u.onend=()=>{i++;setTimeout(play,i===1?260:150)};u.onerror=()=>{i++;play()};speechSynthesis.speak(u)};play()}
function speakFeedback(text=currentFeedback){if(text)systemSpeakFeedback(text)}
if("speechSynthesis" in window){loadVoiceOptions();speechSynthesis.onvoiceschanged=loadVoiceOptions}
$("#playVoice").onclick=()=>speakFeedback();$("#modalPlay").onclick=()=>speakFeedback();$("#closeFeedback").onclick=()=>$("#feedbackModal").classList.add("hidden");$("#goFeedback").onclick=()=>{$("#feedbackModal").classList.add("hidden");document.querySelector('[data-tab="history"]').click()};
function updateMascot(rows){const dates=[...new Set(rows.map(x=>x.payload?.logDate).filter(Boolean))],set=new Set(dates);let streak=0,d=new Date();for(let i=0;i<60;i++){const ds=d.toLocaleDateString("en-CA");if(set.has(ds))streak++;else if(i>0)break;d.setDate(d.getDate()-1)}const total28=dates.filter(x=>(Date.now()-new Date(x+"T12:00:00").getTime())/864e5<=28).length,stage=total28>=16?3:total28>=9?2:total28>=4?1:0,m=$("#mascot");m.className=`mascot stage-${stage} motion-${new Date().getDate()%3}`;$("#streakBadge").textContent=`连续 ${streak} 天`;const titles=["今天，从第一步开始","肚子在退，状态在来","力量已经看得见","你正在成为自己的高光"];$("#mascotTitle").textContent=titles[stage];$("#mascotSub").textContent=`近28天已记录 ${total28} 天 · 再坚持就会继续进化`}
$("#refreshReport").onclick=async()=>{await ensureRows(true);renderCoach(allRows)};
function starterPlan(){return `<section class="report-card action"><h3>第1周基础计划</h3><p>当前还没有个人记录，先按低至中等强度建立节奏；保存首条记录后自动调整。</p><ol><li><b>周一｜上肢 A：</b>器械推胸、坐姿划船、高位下拉、侧平举、二头弯举；每项 2–3 组 × 8–12 次。</li><li><b>周二｜下肢 A：</b>腿举、坐姿腿弯举、臀桥、提踵；每项 2–3 组 × 8–12 次。</li><li><b>周三或周六｜快走：</b>30 分钟，以能完整说短句为准，不冲刺。</li><li><b>周四｜上肢 B：</b>上斜器械推胸、胸托划船、器械肩推、面拉、三头下压；每项 2–3 组 × 8–12 次。</li><li><b>周五｜下肢 B：</b>腿屈伸、罗马尼亚硬拉轻重量、分腿蹲扶稳、提踵；每项 2–3 组 × 8–12 次。</li></ol></section><section class="report-card safety"><h3>通用安全规则</h3><ul><li>保留 3 次余力，不做极限重量和力竭组。</li><li>动作平稳、正常呼吸；疼痛、胸闷、头晕或视力异常立即停止。</li><li>有手术史、心血管或眼部特殊情况，应先在记录中说明，计划再针对性调整。</li></ul></section>`}
function renderCoach(rows){$("#coachLoading").classList.add("hidden");$("#coachReport").classList.remove("hidden");if(!rows.length){$("#coachReport").innerHTML=starterPlan();return}const recent=[...rows].sort((a,b)=>String(a.payload?.logDate||"").localeCompare(String(b.payload?.logDate||""))).slice(-14),ps=recent.map(x=>x.payload||{}),avgSleep=avg(ps,"sleepHours"),avgWake=avg(ps,"wakeCount"),avgEnergy=avg(ps,"energy"),avgRest=avg(ps,"restingHr"),avgComp=avg(ps,"completion"),sessions=ps.filter(p=>p.duration>0).length,minutes=sum(ps,"duration"),last=ps.at(-1)||{};let score=70;if(avgSleep!==null)score+=clamp((avgSleep-6.5)*10,-18,12);if(avgWake!==null)score+=clamp((1.5-avgWake)*5,-14,7);if(avgEnergy!==null)score+=clamp((avgEnergy-3)*7,-14,14);if(avgComp!==null)score+=clamp((avgComp-75)/4,-8,6);score=Math.round(clamp(score,30,96));const warnings=[];if(last.maxHr>=150)warnings.push(`最近一次最高心率 ${last.maxHr}：记录当时感受。若伴胸闷、头晕、异常心悸应停止训练并就医。`);if(hasSymptom(last.symptoms))warnings.push(`最近一次记录了身体异常：“${esc(last.symptoms)}”。下一次先降量，并根据症状决定是否就医。`);if(avgSleep!==null&&avgSleep<7)warnings.push(`近 ${recent.length} 次平均睡眠 ${fmt(avgSleep)} 小时，低于增肌恢复所需的优先目标。`);const advice=buildAdvice({score,avgSleep,avgWake,sessions,minutes});$("#coachReport").innerHTML=`<section class="score-card"><div><p>当前恢复准备度</p><strong>${score}</strong><span>/100</span></div><div class="score-copy"><b>${score>=80?'状态良好':score>=65?'可以训练，控制强度':'优先恢复，建议降量'}</b><small>依据最近 ${recent.length} 条记录动态计算</small></div></section><section class="metric-grid">${metric("平均睡眠",avgSleep,"小时",trend(ps,"sleepHours"))}${metric("平均夜醒",avgWake,"次",avgWake!==null&&avgWake>2?"需改善":"稳定")}${metric("晨间心率",avgRest,"bpm",trend(ps,"restingHr"))}${metric("计划完成",avgComp,"%",avgComp!==null&&avgComp>=80?"良好":"观察")}</section>${trendChart(ps)}<section class="report-card"><h3>本期判断</h3><ul>${advice.summary.map(x=>`<li>${x}</li>`).join("")}</ul></section><section class="report-card action"><h3>下一次训练处方</h3><ol>${advice.next.map(x=>`<li>${x}</li>`).join("")}</ol></section><section class="report-card safety"><h3>你的固定安全边界</h3><ul><li>双眼人工晶体双点悬挂：不跑跳、不冲击、不剧烈震动，器械起落保持平稳。</li><li>力量训练全程呼气发力，不憋气；保留 2–4 次余力（RIR 2–4），不做力竭组和极限重量测试。</li><li>快走建议心率 105–125 次/分，30–45 分钟；能完整说短句，避免冲刺。</li></ul></section>${warnings.length?`<section class="report-card warning"><h3>本期风险提示</h3><ul>${warnings.map(x=>`<li>${x}</li>`).join("")}</ul></section>`:""}<p class="generated">生成时间：${new Date().toLocaleString("zh-CN",{hour12:false})} · 数据范围：最近 ${recent.length} 条</p>`}
function buildAdvice(s){const summary=[],next=[];if(s.avgSleep!==null)summary.push(s.avgSleep>=7?`平均睡眠 ${fmt(s.avgSleep)} 小时，时长基本达标；继续重点观察夜醒。`:`平均睡眠仅 ${fmt(s.avgSleep)} 小时，当前增肌瓶颈更可能是恢复而不是训练量。`);else summary.push("睡眠数据不足，连续记录 7 天后才能判断恢复趋势。");if(s.avgWake!==null&&s.avgWake>=2)summary.push(`平均夜醒 ${fmt(s.avgWake)} 次，睡眠连续性仍是首要改善项。`);summary.push(s.sessions>=4?`记录期内完成 ${s.sessions} 次训练、${Math.round(s.minutes)} 分钟，频率足够，暂不增加训练日。`:`记录期内有 ${s.sessions} 次有效训练，先建立稳定的周一、二、四、五节奏。`);if(s.score<65)next.push("把原计划总组数减少约 25%，所有动作保留 3–4 次余力。","取消额外有氧；训练后用 10–15 分钟轻松步行收尾。");else next.push("按原计划训练，但每个动作只在动作稳定、无憋气时增加次数或小幅加重。","复合动作 RIR 3，孤立动作 RIR 2–3；组间休息 90–150 秒。");next.push("下午训练尽量在睡前 4 小时结束；训练后补充含蛋白质的一餐并正常分次补水。","若安排快走：周三或周六 30–45 分钟，心率 105–125 次/分，不追求距离和步数纪录。");return{summary,next}}
function trendChart(ps){const values=ps.map(p=>Number(p.sleepHours)||0),max=Math.max(8,...values);return `<section class="trend-card"><div class="trend-title"><h3>睡眠趋势</h3><small>最近 ${values.length} 次</small></div><div class="bars">${values.map((v,i)=>`<div class="bar-wrap" title="${esc(ps[i].logDate||'')} ${v||'—'}h"><i style="height:${v?Math.max(12,v/max*100):5}%"></i><small>${v||'—'}</small></div>`).join("")}</div></section>`}
function metric(name,value,unit,status){return `<div class="metric"><small>${name}</small><b>${value===null?'—':fmt(value)}<em>${value===null?'':unit}</em></b><span>${status||'记录中'}</span></div>`}
function avg(ps,k){const a=ps.filter(p=>p[k]!==null&&p[k]!==undefined&&p[k]!=="").map(p=>Number(p[k])).filter(Number.isFinite);return a.length?a.reduce((x,y)=>x+y,0)/a.length:null}function sum(ps,k){return ps.reduce((n,p)=>n+(Number(p[k])||0),0)}function trend(ps,k){const a=ps.filter(p=>p[k]!==null&&p[k]!==undefined&&p[k]!=="").map(p=>Number(p[k])).filter(Number.isFinite);if(a.length<4)return"数据积累中";const h=Math.floor(a.length/2),d=avgNums(a.slice(h))-avgNums(a.slice(0,h));if(Math.abs(d)<.5)return"基本稳定";return d>0?"近期上升":"近期下降"}function avgNums(a){return a.reduce((x,y)=>x+y,0)/a.length}function hasSymptom(s){return s&&!["无","没有","正常","暂无"].includes(String(s).trim())}function clamp(n,a,b){return Math.max(a,Math.min(b,n))}function fmt(n){return n===null?"—":Number(n).toFixed(1).replace(".0","")}function shortDate(d){const[,m,day]=d.split("-");return `${Number(m)}月${Number(day)}日`}function esc(s){return String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}function block(n,v){return v?`<p class="detail"><small>${n}</small><br>${esc(v)}</p>`:""}
function appendMissedPlan(rows){const now=new Date(),y=new Date(now);y.setDate(now.getDate()-1);const day=y.getDay(),map={1:"上肢 A",2:"下肢 A",4:"上肢 B",5:"下肢 B"},missed=map[day];if(!missed)return;const ymd=y.toLocaleDateString("en-CA"),done=rows.some(x=>x.payload?.logDate===ymd&&Number(x.payload?.duration)>0);if(done)return;const box=document.createElement("section");box.className="report-card rescue";box.innerHTML=`<h3>漏训补救 · ${esc(missed)}</h3><p>检测到昨天是计划训练日，但没有有效训练记录。今天不要把两天训练硬塞在一起。</p><ol><li>若恢复评分 ≥65：安排 30–40 分钟缩短版，每个动作 2 组、RIR 3，不做力竭。</li><li>若今天本来也是训练日：优先完成今天计划，把漏训移动到周三或周六；两次力量训练至少间隔 24 小时。</li><li>若睡眠不足 6 小时、夜醒明显或有身体异常：本次不补，做 20–30 分钟轻松快走和活动度练习。</li></ol>`;$("#coachReport").prepend(box)}
const baseRenderCoach=renderCoach;renderCoach=function(rows){baseRenderCoach(rows);appendMissedPlan(rows)};
trendChart=function(ps){const series=[{name:"睡眠",key:"sleepHours",unit:"h",color:"sleep"},{name:"最高心率",key:"maxHr",unit:"",color:"heart"},{name:"完成度",key:"completion",unit:"%",color:"done"}];return `<section class="trend-card"><div class="trend-title"><h3>近期开启趋势</h3><small>最近 ${ps.length} 次记录</small></div><div class="chart-stack">${series.map(s=>{const vals=ps.map(p=>Number(p[s.key])||0),max=Math.max(1,...vals);return `<div class="chart-row"><b>${s.name}</b><div class="mini-bars ${s.color}">${vals.map((v,i)=>`<i style="height:${v?Math.max(8,v/max*100):4}%" title="${esc(ps[i].logDate||'')} ${v||'—'}${s.unit}"></i>`).join("")}</div><span>${vals.at(-1)||'—'}${vals.at(-1)?s.unit:''}</span></div>`}).join("")}</div></section>`};
updateMascot=function(rows){const dates=[...new Set(rows.map(x=>x.payload?.logDate).filter(Boolean))].sort(),set=new Set(dates),trainingDays=new Set([1,2,4,5]);let streak=0,d=new Date();for(let i=0;i<80;i++){if(trainingDays.has(d.getDay())){const ds=d.toLocaleDateString("en-CA");if(set.has(ds))streak++;else if(ds!==today())break}d.setDate(d.getDate()-1)}const completed=dates.length,cycleDay=Math.min(Math.max(completed-1,0),27),stage=Math.min(Math.floor(cycleDay/7),3),col=cycleDay%7,row=Math.floor(cycleDay/7),m=$("#mascot"),latest=[...rows].sort((a,b)=>String(a.payload?.logDate||"").localeCompare(String(b.payload?.logDate||""))).at(-1)?.payload||{};m.className=`mascot tiger cycle-day-${cycleDay+1} stage-${stage}`;m.style.backgroundPosition=`${col/6*100}% ${row/3*100}%`;m.setAttribute("aria-label",`虎虎训练搭子，第${cycleDay+1}天动作，第${stage+1}成长阶段`);$("#streakBadge").textContent=`训练日连签 ${streak}`;const titles=["圆滚滚也要认真出发","动作稳了，身体也轻快了","腰围在收，力量在长","强壮虎上线，萌还是照样萌"],daily=["第一步最难，你已经跨出来了","累了也没有逃跑，这就叫勇气","今天的认真，虎虎替你记住了","慢一点没关系，方向对就很好","喝口水，我们再稳稳向前","你不需要证明自己，只需要照顾好自己","今天完成一点，也比放弃强","身体正在悄悄回应你的坚持","动作做稳，比数字漂亮更重要","别急着变强，先学会长期出现","恢复好的人，才有力气走得远","你今天的状态，值得被认真对待","能坚持记录，就是很了不起","已经走到一半了，虎虎真为你高兴","肩背挺起来的样子，很有精神","不用和别人比，你比昨天更稳了","今天的每一次呼吸都算努力","你正在把计划，慢慢变成习惯","感觉累就减一点，照样是好训练","你的身体不是任务，是长期搭档","今天做得稳，明天才有余地","看得见的变化，来自看不见的坚持","虎虎已经能感受到你的力量了","你愿意回来，就永远不算晚","认真吃饭、好好睡觉，也是训练","今天的你很可靠，说练就来","这段路你不是一个人，虎虎一直在","28天完成！别急着冲刺，我们继续稳稳变好"];let title=titles[stage],sub=`成长周期第 ${cycleDay+1}/28 天 · 已完成 ${completed} 个有效记录日`,mood=daily[cycleDay];const danger=redFlagReason(latest);if(danger){title="虎虎今天先陪你停下来";sub=`检测到“${danger}” · 暂停训练并确认身体状况`;mood="会保护自己，不是退缩，是成熟"}else if(latest.sleepHours&&latest.sleepHours<6.5){title="昨晚没睡够，今天温柔一点";sub=`睡眠 ${latest.sleepHours} 小时 · 建议降量，不追求加重`;mood="少练一点不叫退步，恢复也是训练"}else if(latest.logDate===today()){title="今天的你，被虎虎认真看见了";mood=`${userName||"你"}，这次记录算数，这次努力也算数`}else if(dates.length&&latest.logDate!==today()){title="虎虎在这里等你回来";mood="漏一天不会毁掉计划，今天重新开始就好"}$("#mascotTitle").textContent=title;$("#mascotSub").textContent=sub;if($("#mascotMood"))$("#mascotMood").textContent=`💛 ${mood}`};
const originalFeedbackFor=feedbackFor;
function redFlagReason(p={}){const text=`${p.symptoms||""} ${p.eyeStatus||""}`,has=v=>v!==null&&v!==undefined&&v!=="";if(/胸痛|胸疼|胸闷|呼吸困难|晕厥|昏厥|视力变化|眼痛|异常心悸/.test(text))return String(p.symptoms||p.eyeStatus).trim();if(has(p.restingHr)&&(Number(p.restingHr)>130||Number(p.restingHr)<35))return`静息心率 ${p.restingHr}`;if(has(p.maxHr)&&Number(p.maxHr)>220)return`最高心率 ${p.maxHr}`;if(has(p.avgHr)&&Number(p.avgHr)>190)return`平均心率 ${p.avgHr}`;return""}
feedbackFor=function(p){const reason=redFlagReason(p);if(!reason){const base=originalFeedbackFor(p);return p&&Number(p.recordCompleteness)<100?`${base}\n\n今天的记录完整度是 ${p.recordCompleteness}%。这次先按已有信息分析；明天补齐晨间、训练前后、饮食和晚间五个节点，我才能更准确地调整计划。`:base}return`${userName}，我先不评价今天的完成度。你记录了“${reason}”，这比训练表现更重要。\n\n今天停止训练，不补课、不快走、不测试重量。若症状正在发生、反复出现或加重，请及时就医；若心率数字来自误填，也请先更正记录。\n\n原因没有确认前，我不会给你生成下一次训练处方。先把安全守住，训练以后还有很多机会。`};
const normalRenderCoach=renderCoach;
renderCoach=function(rows){const sorted=[...rows].sort((a,b)=>String(a.payload?.logDate||"").localeCompare(String(b.payload?.logDate||""))),last=sorted.at(-1)?.payload||{},reason=redFlagReason(last);if(!reason){normalRenderCoach(rows);const ownerSpecific=sorted.some(x=>x.payload?.eyeProtection===true||false);if(!ownerSpecific){const safety=[...document.querySelectorAll("#coachReport .safety")].find(x=>x.querySelector("h3")?.textContent.includes("安全边界"));if(safety)safety.innerHTML='<h3>通用安全边界</h3><ul><li>动作平稳、正常呼吸，不做极限重量和力竭组。</li><li>疼痛、胸闷、头晕、异常心悸或视力异常立即停止。</li><li>如有手术史或医生限制，请在记录中明确填写，计划才会采用对应限制。</li></ul>'}return}$("#coachLoading").classList.add("hidden");$("#coachReport").classList.remove("hidden");$("#coachReport").innerHTML=`<section class="report-card warning"><h3>已暂停自动训练处方</h3><p>最近一次记录出现需要先确认的信号：<b>${esc(reason)}</b>。</p><ol><li>今天停止力量训练、有氧和补训，不用训练去验证身体是否没事。</li><li>若症状正在发生、反复或加重，及时就医；胸痛伴呼吸困难、晕厥等情况应立即寻求急救。</li><li>若是手表或录入错误，请先重新核对数据；确认无异常后再保存一条正确记录。</li></ol></section><section class="report-card safety"><h3>当前唯一计划：恢复与核实</h3><ul><li>记录症状发生时间、持续多久、当时动作和心率。</li><li>正常进食、分次补水、保证睡眠，不饮酒。</li><li>原因确认前不生成加重、加组或补课建议。</li></ul></section><p class="generated">生成时间：${new Date().toLocaleString("zh-CN",{hour12:false})} · 安全拦截已启用</p>`};
const previousStarterPlan=starterPlan;
starterPlan=function(){return previousStarterPlan().replace("你的固定安全边界","通用安全边界")};
ensureRows();

// Product upgrade: lightweight daily cockpit and transparent coaching evidence.
const cockpit=document.createElement("section");cockpit.id="todayCockpit";cockpit.className="today-cockpit";cockpit.innerHTML='<div class="cockpit-head"><div><p class="kicker">TODAY\'S NEXT MOVE</p><h2>今天下一步</h2></div><span id="cockpitReadiness" class="cockpit-status">待填写</span></div><div class="cockpit-grid"><div><small>建议动作</small><b id="cockpitNext">先完成晨间恢复</b></div><div><small>本周训练</small><b id="cockpitWeek">0 / 4 次</b></div><div><small>记录质量</small><b id="cockpitQuality">0%</b></div></div><p id="cockpitReason" class="cockpit-reason">先记录睡眠、精力与身体状态，计划才会更准确。</p>';
$("#formView")?.insertBefore(cockpit,$("#moduleStrip"));
function recordQuality(){const f=$("#logForm")?.elements;if(!f)return 0;const checks=[f.sleepHours?.value,f.energy?.value,f.eyeStatus?.value,f.sessionType?.value,f.duration?.value,f.completion?.value,f.rpe?.value,f.meals?.value,f.symptoms?.value],filled=checks.filter(v=>String(v??"").trim()!=="").length;return Math.round(filled/checks.length*100)}
function renderProductCockpit(rows=[]){if(!$("#todayCockpit"))return;const done=completedModules(),nextKey=Object.keys(moduleNames).find(x=>!done.includes(x)),f=$("#logForm").elements,sleep=Number(f.sleepHours?.value||0),energy=Number(f.energy?.value||0),eye=f.eyeStatus?.value||"",symptoms=`${f.preSymptoms?.value||""} ${f.postSymptoms?.value||""} ${f.symptoms?.value||""}`;let status="可以推进",reason="按今天计划稳定完成，不憋气、不震动、不力竭。",next=nextKey?`完成${moduleNames[nextKey]}记录`:"五项已齐，可以生成完整日报";if(eye==="视力变化或眼痛"||/胸闷|胸痛|头晕|晕厥|视力变化|眼痛|异常心悸/.test(symptoms)){status="暂停训练";reason="检测到需要优先确认的身体信号。今天不补训、不测试重量。";next="先处理身体异常"}else if((sleep&&sleep<6)||(energy&&energy<=2)){status="建议降量";reason="恢复不足：训练总组数减少约25%，保留3–4次余力。";next=nextKey?`先完成${moduleNames[nextKey]}`:"改为恢复或缩短版"}const now=new Date(),monday=new Date(now);monday.setDate(now.getDate()-((now.getDay()+6)%7));monday.setHours(0,0,0,0);const weekSessions=rows.filter(x=>{const p=x.payload||{},dt=new Date((p.logDate||"")+"T12:00:00");return dt>=monday&&Number(p.duration)>0}).length;$("#cockpitReadiness").textContent=status;$("#cockpitReadiness").className=`cockpit-status ${status==="暂停训练"?"stop":status==="建议降量"?"reduce":"ready"}`;$("#cockpitNext").textContent=next;$("#cockpitWeek").textContent=`${weekSessions} / 4 次`;$("#cockpitQuality").textContent=`${recordQuality()}%`;$("#cockpitReason").textContent=reason}
$("#logForm")?.addEventListener("input",()=>renderProductCockpit(allRows));document.querySelectorAll(".module-save").forEach(btn=>btn.addEventListener("click",()=>setTimeout(()=>renderProductCockpit(allRows),0)));renderProductCockpit([]);
const productEnsureRows=ensureRows;ensureRows=async function(force=false){const rows=await productEnsureRows(force);renderProductCockpit(rows);return rows};
const productRenderDailyFeedback=renderDailyFeedback;renderDailyFeedback=function(p){productRenderDailyFeedback(p);if(!p)return;const items=[["睡眠",p.sleepHours!=null?`${p.sleepHours}小时`:"未填"],["训练",p.duration!=null?`${p.duration}分钟 · 完成度${p.completion??"—"}%`:"未填"],["强度",p.rpe!=null?`RPE ${p.rpe}`:"未填"],["身体",p.symptoms||"未填"],["记录",`${p.recordCompleteness??0}%完整`]],known=items.filter(x=>!String(x[1]).includes("未填")).length,confidence=known>=5?"高":known>=3?"中":"低",box=document.createElement("section");box.className="feedback-evidence";box.innerHTML=`<div class="evidence-head"><b>这份反馈依据什么</b><span>可信度 ${confidence}</span></div><div class="evidence-grid">${items.map(x=>`<div><small>${esc(x[0])}</small><strong>${esc(String(x[1]))}</strong></div>`).join("")}</div><p>${confidence==="低"?"当前信息不足，建议补齐睡眠、训练强度和身体反应后再调整计划。":"反馈只基于你本账户的已保存记录，不与其他用户数据混用。"}</p>`;$("#dailyFeedback")?.appendChild(box)};
setTimeout(async()=>renderProductCockpit(await ensureRows()),500);

// Per-account training profile. It travels with saved records and is restored with the account.
function profileStorageKey(){return`fitness-profile-${key.slice(0,12)||"guest"}`}function loadProfile(){try{return JSON.parse(localStorage.getItem(profileStorageKey())||"{}")}catch{return{}}}function saveProfileData(data){localStorage.setItem(profileStorageKey(),JSON.stringify(data))}
const profilePanel=document.createElement("section");profilePanel.className="account-profile";profilePanel.innerHTML='<p class="kicker">TRAINING PROFILE</p><h3>我的训练档案</h3><p>教练反馈会结合这些基础条件，不会套用别人的计划。</p><div class="grid two"><label>出生年份<input id="profileBirthYear" type="number" min="1920" max="2020" placeholder="例如 1984"></label><label>身高（cm）<input id="profileHeight" type="number" min="100" max="230"></label><label>体重（kg）<input id="profileWeight" type="number" min="25" max="300" step="0.1"></label><label>每周计划训练<select id="profileWeeklyDays"><option value="">请选择</option><option value="2">2天</option><option value="3">3天</option><option value="4">4天</option><option value="5">5天</option><option value="6">6天</option></select></label></div><label>主要目标<select id="profileGoal"><option value="">请选择</option><option>改善睡眠与增肌</option><option>增肌</option><option>减脂</option><option>提升体能</option><option>保持健康</option></select></label><label>训练条件<select id="profileEquipment"><option value="">请选择</option><option>专业健身房</option><option>家庭少量器械</option><option>徒手训练</option></select></label><label>伤病、手术史与医生限制<textarea id="profileConstraints" rows="3" placeholder="没有写“无”；如有眼科、心血管、腰椎等限制请具体填写"></textarea></label><button id="saveProfile" class="small-btn" type="button">保存训练档案</button>';
profilePanel.querySelector(".grid")?.insertAdjacentHTML("beforeend",'<label>生理性别（仅用于代谢估算）<select id="profileSex"><option value="male">男</option><option value="female">女</option><option value="unspecified">不指定</option></select></label>');
$("#boundAccount")?.insertBefore(profilePanel,$("#boundAccount p"));
function hydrateProfile(){const p=loadProfile(),map={profileBirthYear:"birthYear",profileHeight:"height",profileWeight:"weight",profileWeeklyDays:"weeklyDays",profileGoal:"goal",profileEquipment:"equipment",profileConstraints:"constraints",profileSex:"sex"};Object.entries(map).forEach(([id,k])=>{if($("#"+id))$("#"+id).value=p[k]??(k==="sex"?"male":"")})}function readProfileUI(){return{birthYear:Number($("#profileBirthYear")?.value)||null,height:Number($("#profileHeight")?.value)||null,weight:Number($("#profileWeight")?.value)||null,weeklyDays:Number($("#profileWeeklyDays")?.value)||null,goal:$("#profileGoal")?.value||"",equipment:$("#profileEquipment")?.value||"",constraints:$("#profileConstraints")?.value.trim()||"",sex:$("#profileSex")?.value||"male"}}hydrateProfile();$("#saveProfile")?.addEventListener("click",()=>{saveProfileData(readProfileUI());syncEnergyFields();note("训练档案已保存，之后的反馈和计划会使用这些条件")});
const profileInput=document.createElement("input");profileInput.type="hidden";profileInput.name="profileJson";$("#logForm")?.appendChild(profileInput);$("#logForm")?.addEventListener("submit",()=>{profileInput.value=JSON.stringify(loadProfile())},{capture:true});
const profileEnsureRows=ensureRows;ensureRows=async function(force=false){const rows=await profileEnsureRows(force),remote=rows.map(x=>x.payload?.profileJson).find(Boolean);if(!Object.keys(loadProfile()).length&&remote){try{saveProfileData(typeof remote==="string"?JSON.parse(remote):remote);hydrateProfile()}catch{}}return rows};
function profileFor(p={}){try{return p.profileJson?typeof p.profileJson==="string"?JSON.parse(p.profileJson):p.profileJson:loadProfile()}catch{return loadProfile()}}function proteinCoverage(text=""){return["蛋","奶","酸奶","鸡","鱼","虾","牛","猪","豆","蛋白粉"].filter(x=>String(text).includes(x)).length}
feedbackFor=function(p){if(!p)return`${userName}，今天还没有完整记录。先填睡眠、训练和饮食中的任意一项，我就能开始给你有依据的建议。`;const reason=redFlagReason(p);if(reason)return`${userName}，今天最重要的不是完成训练，而是先处理“${reason}”。暂停力量训练、快走和补训；如果症状正在发生、反复或加重，请及时就医。等原因确认后，我们再安全地接上计划。`;const profile=profileFor(p),age=profile.birthYear?new Date().getFullYear()-profile.birthYear:null,weight=Number(p.bodyWeight||profile.weight||0),session=p.sessionType||"本次训练",duration=Number(p.duration||0),completion=Number(p.completion||0),rpe=Number(p.rpe||0),sleep=Number(p.sleepHours||0),wake=Number(p.wakeCount||0),protein=proteinCoverage(p.meals),parts=[];parts.push(`${userName}，我把你今天的训练、恢复和饮食放在一起看了。${age?`你目前约 ${age} 岁，`:""}${profile.goal?`目标是“${profile.goal}”。`:""}${duration?`今天完成了 ${duration} 分钟${session}，计划完成度 ${completion||"未填"}%。`:"今天没有有效训练时长，这一天按恢复日评价。"}`);let training="";if(!duration)training="训练方面：今天不需要补偿性加练。先把身体状态和下一次训练准备好。";else if(rpe>=9)training=`训练方面：RPE ${rpe} 偏高。下一次维持重量或减少一组，避免连续把训练做成力竭测试。`;else if(completion>=80)training=`训练方面：完成度 ${completion}%，训练刺激已经够用。下一次只有在动作稳定、正常呼吸且保留余力时，才增加1次重复或最小重量。`;else training=`训练方面：完成度 ${completion||"未填"}%。先保证核心动作质量，不用靠额外组数追回进度。`;parts.push(training);let recovery="恢复方面：";if(sleep&&sleep<6.5)recovery+=`睡眠只有 ${sleep} 小时，是今天最明显的限制因素。下一次总训练量减少约25%，RIR保留3–4。`;else if(wake>=2)recovery+=`睡眠时长不一定差，但夜醒 ${wake} 次影响连续性。今天不加训练量，下午训练尽量在睡前4小时结束。`;else recovery+="目前没有看到明显恢复警报，可以继续原计划，但仍以动作稳定和不力竭为边界。";parts.push(recovery);let nutrition="饮食方面：";if(!String(p.meals||"").trim())nutrition+="信息不足，暂时不能可靠判断摄入是否支持增肌；至少记录每餐的蛋白质来源和大致份量。";else if(protein===0)nutrition+="记录里没有识别到明确蛋白质来源。下一餐优先补充蛋、奶、鱼、禽、瘦肉或豆制品中的一种。";else nutrition+=`记录中看到了 ${protein} 类蛋白质来源，这是好信号。${weight?`以体重约 ${weight} kg估算，运动人群全天蛋白质可先参考约 ${Math.round(weight*1.4)}–${Math.round(weight*2)} g，再分散到各餐；照片无法精确计算克数，所以先把份量写清楚。`:"补充体重后，我可以给出更具体的全天蛋白质参考范围。"}`;parts.push(nutrition);parts.push(`下一步：${duration?"今天到这里就够了，正常吃饭、分次补水、按时睡觉；下一次继续原节奏，不临时加码。":"把今天当恢复日，明天根据睡眠和身体状态决定是否恢复训练。"}你不是靠一次拼命变强，而是靠每次都做出合适的决定。我们继续。`);return parts.join("\n\n")};
const evidenceRender=renderDailyFeedback;renderDailyFeedback=function(p){evidenceRender(p);if(!p)return;const sources=document.createElement("details");sources.className="feedback-sources";sources.innerHTML='<summary>专业依据与使用边界</summary><p>训练建议参考ACSM抗阻训练进阶原则；蛋白质范围参考ISSN运动营养立场声明；不要求每组力竭的判断参考抗阻训练力竭与非力竭系统综述。文献给出通用范围，最终处方仍依据你的账户档案、当天记录与医生限制调整。</p><div><a target="_blank" rel="noopener" href="https://pubmed.ncbi.nlm.nih.gov/41843416/">ACSM抗阻训练立场声明</a><a target="_blank" rel="noopener" href="https://pubmed.ncbi.nlm.nih.gov/28642676/">ISSN蛋白质立场声明</a><a target="_blank" rel="noopener" href="https://pubmed.ncbi.nlm.nih.gov/33497853/">力竭与非力竭系统综述</a></div>';$("#dailyFeedback")?.appendChild(sources)};
const accountCoachRender=renderCoach;renderCoach=function(rows){accountCoachRender(rows);const latest=[...rows].sort((a,b)=>String(a.payload?.logDate||"").localeCompare(String(b.payload?.logDate||""))).at(-1)?.payload||{},profile=profileFor(latest),limits=String(profile.constraints||""),safety=[...document.querySelectorAll("#coachReport .safety")].find(x=>x.querySelector("h3")?.textContent.includes("安全边界"));if(safety&&limits&&!/^(无|没有|正常)$/.test(limits)){const rules=["动作平稳、正常呼吸，不做极限重量和力竭组。"];if(/眼|晶体|玻切|视网膜/.test(limits))rules.push("涉及眼科手术或眼部限制：不跑跳、不冲击、不剧烈震动；出现视力变化或眼痛立即停止。");if(/腰|椎间盘|颈|肩/.test(limits))rules.push("涉及脊柱或关节限制：避免诱发疼痛的幅度与负重，优先器械支撑和中立位。");if(/心|主动脉|血压|马凡/.test(limits))rules.push("涉及心血管风险：避免憋气和极限负重，运动强度与心率范围应以医生意见为先。");rules.push(`账户档案记录的限制：${esc(limits)}`);safety.innerHTML=`<h3>本账户安全边界</h3><ul>${rules.map(x=>`<li>${x}</li>`).join("")}</ul>`}};

// Popular strength-app patterns, implemented locally without heavy dependencies.
function parseExerciseLines(text=""){return String(text).split(/\n+/).map(line=>{const name=line.split(/[｜|]/)[0]?.trim(),nums=[...line.matchAll(/(?:重量|weight)[:：]\s*([\d.]+)|(?:组数|sets?)[:：]\s*(\d+)|(?:次数|reps?)[:：]\s*(\d+)|RIR[:：]\s*([\d.]+)/gi)];let weight=null,sets=null,reps=null,rir=null;nums.forEach(m=>{if(m[1]!=null)weight=Number(m[1]);if(m[2]!=null)sets=Number(m[2]);if(m[3]!=null)reps=Number(m[3]);if(m[4]!=null)rir=Number(m[4])});return{name,weight,sets,reps,rir,volume:weight&&sets&&reps?weight*sets*reps:null}}).filter(x=>x.name&&!/^动作/.test(x.name))}
function progressionInsights(p,rows){const current=parseExerciseLines(p.exercises);if(!current.length)return[];const previous=[...rows].filter(x=>x.payload!==p&&x.payload?.sessionType===p.sessionType&&x.payload?.exercises).sort((a,b)=>String(b.payload.logDate||"").localeCompare(String(a.payload.logDate||""))).at(0)?.payload,old=new Map(parseExerciseLines(previous?.exercises).map(x=>[x.name,x]));return current.slice(0,6).map(x=>{const before=old.get(x.name);if(!before)return{name:x.name,label:"建立基线",advice:"先把动作、重量、次数和RIR记完整"};if(x.rir!=null&&x.rir<=1)return{name:x.name,label:"疲劳偏高",advice:"下次维持或降量，不加重"};if(x.volume&&before.volume){const change=Math.round((x.volume/before.volume-1)*100);if(change>=5)return{name:x.name,label:`容量 +${change}%`,advice:"先巩固一次，再考虑最小幅度加重"};if(change<=-10)return{name:x.name,label:`容量 ${change}%`,advice:"结合睡眠和动作质量判断，不急着追回"};}if(x.reps&&x.reps>=12&&(x.rir??3)>=2)return{name:x.name,label:"达到次数上限",advice:"动作稳定时可增加最小重量"};return{name:x.name,label:"稳定完成",advice:"下次优先增加1次重复"}})}
function daysSinceSession(rows,types){const last=[...rows].filter(x=>types.includes(x.payload?.sessionType)&&Number(x.payload?.duration)>0).sort((a,b)=>String(b.payload.logDate||"").localeCompare(String(a.payload.logDate||""))).at(0)?.payload?.logDate;if(!last)return null;return Math.max(0,Math.floor((Date.now()-new Date(last+"T12:00:00").getTime())/864e5))}
function recoveryPercent(days){if(days==null)return null;return Math.min(100,Math.round(days/3*100))}
function fatigueSignal(rows){const recent=[...rows].sort((a,b)=>String(a.payload?.logDate||"").localeCompare(String(b.payload?.logDate||""))).slice(-3).map(x=>x.payload||{}),hits=recent.filter(p=>(p.sleepHours&&p.sleepHours<6.5)||(p.rpe&&p.rpe>=9)||(p.soreness>=4)||(p.stress>=4)).length;return{hits,deload:recent.length>=3&&hits>=2}}
const copyLastBtn=document.createElement("button");copyLastBtn.id="copyPreviousWorkout";copyLastBtn.className="ghost-btn full";copyLastBtn.type="button";copyLastBtn.textContent="沿用上次同类型训练记录";$("#insertExerciseTemplate")?.insertAdjacentElement("afterend",copyLastBtn);copyLastBtn.addEventListener("click",()=>{const type=$("[name=sessionType]")?.value,last=[...allRows].find(x=>x.payload?.sessionType===type&&x.payload?.exercises);if(!last)return note("还没有同类型历史训练，先使用动作模板");const area=$("[name=exercises]");if(area.value.trim()&&!confirm("当前已有内容，是否替换为上次记录？"))return;area.value=last.payload.exercises;area.dispatchEvent(new Event("input",{bubbles:true}));note("已带入上次动作，请修改今天的重量、次数和RIR")});
const progressionFeedbackRender=renderDailyFeedback;renderDailyFeedback=function(p){progressionFeedbackRender(p);if(!p)return;const insights=progressionInsights(p,allRows);if(!insights.length)return;const card=document.createElement("section");card.className="progression-card";card.innerHTML=`<div class="evidence-head"><b>动作进阶判断</b><span>对比上次同类型训练</span></div><div class="progression-list">${insights.map(x=>`<div><b>${esc(x.name)}</b><em>${esc(x.label)}</em><small>${esc(x.advice)}</small></div>`).join("")}</div>`;$("#dailyFeedback")?.appendChild(card)};
const recoveryCoachRender=renderCoach;renderCoach=function(rows){recoveryCoachRender(rows);if(!rows.length)return;const upperDays=daysSinceSession(rows,["上肢 A","上肢 B"]),lowerDays=daysSinceSession(rows,["下肢 A","下肢 B"]),upper=recoveryPercent(upperDays),lower=recoveryPercent(lowerDays),fatigue=fatigueSignal(rows),card=document.createElement("section");card.className=`report-card recovery-map${fatigue.deload?" warning":""}`;card.innerHTML=`<h3>${fatigue.deload?"建议进入减量训练":"训练恢复地图"}</h3><div class="recovery-bars"><div><span>上肢</span><i><b style="width:${upper??0}%"></b></i><strong>${upper==null?"暂无数据":upper+"%"}</strong></div><div><span>下肢</span><i><b style="width:${lower??0}%"></b></i><strong>${lower==null?"暂无数据":lower+"%"}</strong></div></div><p>${fatigue.deload?`最近3次记录中有 ${fatigue.hits} 次出现睡眠不足、高RPE或高酸痛/压力。下一次总组数减少约30%，重量不增加，RIR保持3–4。`:"恢复百分比按距离最近同部位训练的时间做保守估计，并结合当天酸痛和睡眠决定是否训练；它不是医学指标。"}</p>`;$("#coachReport")?.prepend(card)};

// Structured workout logging: keep the legacy textarea as the storage format so old records remain readable.
const exerciseArea=$("[name=exercises]");
const exerciseAreaLabel=exerciseArea?.closest("label");
const structuredEditor=document.createElement("section");
structuredEditor.id="structuredExerciseEditor";
structuredEditor.className="structured-editor";
structuredEditor.innerHTML='<div class="structured-head"><div><p class="kicker">SET BY SET</p><h3>动作记录</h3></div><span>重量 · 组数 · 次数 · RIR</span></div><p class="structured-help">按计划自动列出动作；只填实际完成的内容。RIR 是做完后还能完成的次数。</p><div id="exerciseRows" class="exercise-rows"></div><button id="addExerciseRow" class="ghost-btn full" type="button">＋ 添加自定义动作</button>';
exerciseAreaLabel?.insertAdjacentElement("beforebegin",structuredEditor);
exerciseAreaLabel?.classList.add("legacy-exercise-field");

function sessionExerciseNames(){return exercisePlans[$("[name=sessionType]")?.value||"上肢 A"]||[]}
function serializeExerciseRows(){const lines=[...document.querySelectorAll(".exercise-entry")].map(row=>{const name=row.querySelector('[data-field="name"]')?.value.trim(),weight=row.querySelector('[data-field="weight"]')?.value,sets=row.querySelector('[data-field="sets"]')?.value,reps=row.querySelector('[data-field="reps"]')?.value,rir=row.querySelector('[data-field="rir"]')?.value;if(!name||![weight,sets,reps,rir].some(v=>String(v).trim()!==""))return"";return`${name}｜重量：${weight||0}｜组数：${sets||0}｜次数：${reps||0}｜RIR：${rir||0}`}).filter(Boolean);if(exerciseArea){exerciseArea.value=lines.join("\n");exerciseArea.dispatchEvent(new Event("input",{bubbles:true}))}renderNextPrescription()}
function exerciseRow(name="",data={}){const row=document.createElement("div");row.className="exercise-entry";row.innerHTML=`<label class="exercise-name">动作<input data-field="name" value="${esc(name)}" placeholder="动作名称"></label><label>重量 kg<input data-field="weight" inputmode="decimal" type="number" min="0" step="0.5" value="${data.weight??""}" placeholder="—"></label><label>组数<input data-field="sets" inputmode="numeric" type="number" min="0" max="20" value="${data.sets??""}" placeholder="—"></label><label>次数<input data-field="reps" inputmode="numeric" type="number" min="0" max="100" value="${data.reps??""}" placeholder="—"></label><label>RIR<input data-field="rir" inputmode="decimal" type="number" min="0" max="10" step="0.5" value="${data.rir??""}" placeholder="2–4"></label><button class="remove-exercise" type="button" aria-label="删除动作">×</button>`;row.querySelectorAll("input").forEach(input=>input.addEventListener("input",serializeExerciseRows));row.querySelector(".remove-exercise").onclick=()=>{row.remove();serializeExerciseRows()};return row}
function renderStructuredExercises(source="plan"){const box=$("#exerciseRows");if(!box)return;const parsed=parseExerciseLines(exerciseArea?.value||""),byName=new Map(parsed.map(x=>[x.name,x])),names=source==="stored"&&parsed.length?parsed.map(x=>x.name):sessionExerciseNames();box.innerHTML="";names.forEach(name=>box.appendChild(exerciseRow(name,byName.get(name)||{})));renderNextPrescription()}
function importLegacyExerciseText(){renderStructuredExercises("stored")}
$("#addExerciseRow")?.addEventListener("click",()=>{$("#exerciseRows")?.appendChild(exerciseRow("",{}));document.querySelector(".exercise-entry:last-child input")?.focus()});
$("[name=sessionType]")?.addEventListener("change",()=>renderStructuredExercises("plan"));
$("#insertExerciseTemplate")?.addEventListener("click",()=>setTimeout(importLegacyExerciseText,0));
$("#copyPreviousWorkout")?.addEventListener("click",()=>setTimeout(importLegacyExerciseText,0));

const prescriptionCard=document.createElement("section");
prescriptionCard.id="nextPrescription";
prescriptionCard.className="next-prescription";
structuredEditor.insertAdjacentElement("afterend",prescriptionCard);
function currentReadiness(){const f=$("#logForm")?.elements||{},sleep=Number(f.sleepHours?.value||0),energy=Number(f.energy?.value||0),soreness=Number(f.soreness?.value||0),stress=Number(f.stress?.value||0),eye=f.eyeStatus?.value||"正常",symptoms=`${f.preSymptoms?.value||""} ${f.postSymptoms?.value||""}`;if(eye==="视力变化或眼痛"||/胸闷|胸痛|头晕|晕厥|视力变化|眼痛|异常心悸/.test(symptoms))return{level:"stop",label:"暂停训练",factor:0,reason:"先确认身体异常，不执行训练处方。"};if(eye==="轻微不适"||(sleep&&sleep<6)||(energy&&energy<=2)||soreness>=4||stress>=4)return{level:"reduce",label:"降量处方",factor:.75,reason:"恢复信号不足：预计总组数减少约25%，RIR 3–4。"};return{level:"ready",label:"正常处方",factor:1,reason:"状态允许时按计划推进；先加次数，达到上限后再加最小重量。"}}
function previousExerciseMap(){const type=$("[name=sessionType]")?.value,last=[...allRows].find(x=>x.payload?.sessionType===type&&x.payload?.exercises);return new Map(parseExerciseLines(last?.payload?.exercises||"").map(x=>[x.name,x]))}
function renderNextPrescription(){if(!prescriptionCard)return;const readiness=currentReadiness(),previous=previousExerciseMap(),names=[...document.querySelectorAll('.exercise-entry [data-field="name"]')].map(x=>x.value.trim()).filter(Boolean),targets=names.slice(0,6).map(name=>{const old=previous.get(name);if(readiness.level==="stop")return`<li><b>${esc(name)}</b><span>今天不执行</span></li>`;if(!old)return`<li><b>${esc(name)}</b><span>建立安全基线 · RIR 3</span></li>`;const sets=Math.max(1,Math.round((old.sets||2)*readiness.factor)),nextReps=readiness.factor<1?old.reps:old.reps?old.reps+1:null;return`<li><b>${esc(name)}</b><span>${old.weight??"原"} kg · ${sets} 组${nextReps?` × ${nextReps} 次`:""} · RIR ${readiness.factor<1?"3–4":Math.max(2,old.rir??3)}</span></li>`}).join("");prescriptionCard.className=`next-prescription ${readiness.level}`;prescriptionCard.innerHTML=`<div class="prescription-head"><div><p class="kicker">NEXT SESSION</p><h3>下一次训练处方</h3></div><span>${readiness.label}</span></div><p>${readiness.reason}</p>${targets?`<ul>${targets}</ul>`:'<div class="prescription-empty">选择训练计划并完成一次记录后，这里会给出逐动作目标。</div>'}<small>处方会随睡眠、精力、酸痛、压力、异常症状及同动作历史自动变化。</small>`}
[$("[name=sleepHours]"),$("[name=energy]"),$("[name=soreness]"),$("[name=stress]"),$("[name=eyeStatus]"),$("[name=preSymptoms]")].filter(Boolean).forEach(el=>el.addEventListener("input",renderNextPrescription));
renderStructuredExercises(exerciseArea?.value.trim()?"stored":"plan");
$("#logForm")?.addEventListener("reset",()=>setTimeout(()=>renderStructuredExercises("plan"),0));
const prescriptionEnsureRows=ensureRows;
ensureRows=async function(force=false){const rows=await prescriptionEnsureRows(force);renderNextPrescription();return rows};

// Cardio and recovery sessions use time, distance and intensity instead of strength units.
const strengthProgressionInsights=progressionInsights;
progressionInsights=function(p,rows){return /快走|恢复|休息/.test(p?.sessionType||"")?[]:strengthProgressionInsights(p,rows)};
const cardioTypes=new Set(["恢复快走","耐力快走"]);
const recoveryTypes=new Set(["恢复 / 休息"]);
const cardioEditor=document.createElement("section");
cardioEditor.id="cardioExerciseEditor";
cardioEditor.className="cardio-editor hidden";
cardioEditor.innerHTML=`<div class="structured-head"><div><p class="kicker">WALK SESSION</p><h3 id="cardioEditorTitle">快走记录</h3></div><span id="cardioTargetBadge">低冲击有氧</span></div><p id="cardioEditorHelp" class="structured-help">记录实际完成的数据；时长和心率仍填写在上方训练表现区。</p><div class="cardio-fields"><label>距离 km<input name="cardioDistance" data-cardio="distance" inputmode="decimal" type="number" min="0" max="100" step="0.01" placeholder="例如 3.2"></label><label>平均配速 分/公里<input name="cardioPace" data-cardio="pace" inputmode="decimal" placeholder="例如 10:30"></label><label>步频 步/分钟<input name="cardioCadence" data-cardio="cadence" inputmode="numeric" type="number" min="0" max="250" placeholder="可选"></label><label>路线/坡度<select name="cardioTerrain" data-cardio="terrain"><option value="平地">平地</option><option value="跑步机 0–2% 坡度">跑步机 0–2% 坡度</option><option value="缓坡">缓坡</option><option value="室内步行">室内步行</option></select></label></div><div class="cardio-zone"><span>建议心率区间</span><b id="cardioZoneText">95–115 次/分</b><small id="cardioSafetyText">能完整说短句；不跑跳、不憋气、不追求速度。</small></div>`;
structuredEditor.insertAdjacentElement("beforebegin",cardioEditor);

function isCardioSession(type=$('[name=sessionType]')?.value||""){return cardioTypes.has(type)}
function isRecoverySession(type=$('[name=sessionType]')?.value||""){return recoveryTypes.has(type)}
function serializeCardioSession(){if(!isCardioSession()&&!isRecoverySession())return;const f=$("#logForm")?.elements||{},type=f.sessionType?.value||"快走",parts=[];if(f.duration?.value)parts.push(`时长：${f.duration.value}分钟`);if(f.cardioDistance?.value)parts.push(`距离：${f.cardioDistance.value}km`);if(f.cardioPace?.value)parts.push(`平均配速：${f.cardioPace.value}/km`);if(f.avgHr?.value)parts.push(`平均心率：${f.avgHr.value}`);if(f.maxHr?.value)parts.push(`最高心率：${f.maxHr.value}`);if(f.cardioCadence?.value)parts.push(`步频：${f.cardioCadence.value}`);if(f.steps?.value)parts.push(`步数：${f.steps.value}`);if(f.rpe?.value)parts.push(`RPE：${f.rpe.value}`);if(f.cardioTerrain?.value)parts.push(`路线：${f.cardioTerrain.value}`);if(exerciseArea){exerciseArea.value=parts.length?`${type}｜${parts.join("｜")}`:"";exerciseArea.dispatchEvent(new Event("input",{bubbles:true}))}}
function renderTrainingEditor(){const type=$('[name=sessionType]')?.value||"上肢 A",cardio=isCardioSession(type),recovery=isRecoverySession(type),endurance=type==="耐力快走";structuredEditor.classList.toggle("hidden",cardio||recovery);cardioEditor.classList.toggle("hidden",!cardio&&!recovery);prescriptionCard.classList.toggle("hidden",cardio||recovery);$("#insertExerciseTemplate")?.classList.toggle("hidden",cardio||recovery);$("#copyPreviousWorkout")?.classList.toggle("hidden",cardio||recovery);if(cardio||recovery){$("#cardioEditorTitle").textContent=recovery?"恢复活动记录":type;$("#cardioTargetBadge").textContent=recovery?"主动恢复":endurance?"耐力有氧":"恢复有氧";$("#cardioEditorHelp").textContent=recovery?"可记录轻松步行或活动度练习；无需填写重量、组数、次数或RIR。":"填写距离、配速与路线；时长、心率、RPE和当天步数仍在原位置填写。";$("#cardioZoneText").textContent=recovery?"以轻松舒适为准":endurance?"100–120 次/分":"95–115 次/分";$("#cardioSafetyText").textContent=recovery?"身体放松、呼吸自然；不把恢复日做成训练日。":"平地快走、能完整说短句；不跑跳、不憋气、不追逐峰值心率。";serializeCardioSession()}else renderStructuredExercises(exerciseArea?.value.trim()?"stored":"plan")}
[$('[name=duration]'),$('[name=avgHr]'),$('[name=maxHr]'),$('[name=rpe]'),$('[name=steps]'),...cardioEditor.querySelectorAll('[data-cardio]')].filter(Boolean).forEach(el=>el.addEventListener("input",serializeCardioSession));
$('[name=sessionType]')?.addEventListener("change",()=>{exerciseArea.value="";renderTrainingEditor()});
const cardioSubmitForm=$("#logForm");
cardioSubmitForm?.addEventListener("submit",serializeCardioSession,true);
cardioSubmitForm?.addEventListener("reset",()=>setTimeout(renderTrainingEditor,0));
renderTrainingEditor();

// A versioned weekly plan makes the coaching decision visible instead of silently changing advice.
const versionedCoachRender=renderCoach;
renderCoach=function(rows){versionedCoachRender(rows);const sorted=[...rows].sort((a,b)=>String(a.payload?.logDate||"").localeCompare(String(b.payload?.logDate||""))),recent=sorted.slice(-7).map(x=>x.payload||{}),fatigue=fatigueSignal(rows),avgSleep7=avg(recent,"sleepHours"),sessions7=recent.filter(x=>Number(x.duration)>0).length,lowRecovery=fatigue.deload||(avgSleep7!==null&&avgSleep7<6.5),isStarter=!rows.length,version=`${new Date().getFullYear()}.${String(new Date().getMonth()+1).padStart(2,"0")}.${String(new Date().getDate()).padStart(2,"0")}`;const card=document.createElement("section");card.className="report-card weekly-version";card.innerHTML=`<div class="weekly-version-head"><div><p class="kicker">WEEK PLAN · V${version}</p><h3>本周自动调整</h3></div><span>${isStarter?"起步周":lowRecovery?"恢复周":"推进周"}</span></div><div class="weekly-grid"><div><small>近7条有效训练</small><b>${sessions7} 次</b></div><div><small>平均睡眠</small><b>${avgSleep7===null?"数据不足":fmt(avgSleep7)+" h"}</b></div><div><small>本周策略</small><b>${isStarter?"先建立安全基线":lowRecovery?"总组数 -25%～30%":"维持频率，逐步进阶"}</b></div></div><ol><li>周一上肢 A、周二下肢 A、周四上肢 B、周五下肢 B；周三或周六安排快走。</li><li>${isStarter?"首周只需稳定完成，保留 RIR 3；保存训练记录后再给出逐动作进阶目标。":lowRecovery?"本周不加重量，复合动作 RIR 3–4；连续两晚恢复改善后再恢复原量。":"同动作达到次数上限且 RIR≥2 时，下次增加最小重量；否则优先每组加1次。"}</li><li>漏训不叠加两堂完整力量课；移动到空闲日或做每动作2组的缩短版。</li></ol><small>版本依据最近记录生成；新记录会生成新的计划版本，不覆盖历史训练数据。</small>`;$("#coachReport")?.prepend(card)};

// Interaction QA patch: visible save states, button feedback and WeChat-friendly speech.
function flashButton(button,text,kind="success",delay=1800){if(!button)return;const original=button.dataset.originalText||button.textContent;button.dataset.originalText=original;button.textContent=text;button.classList.remove("button-success","button-error","button-busy");button.classList.add(`button-${kind}`);button.disabled=kind==="busy";clearTimeout(button._feedbackTimer);if(kind!=="busy")button._feedbackTimer=setTimeout(()=>{button.textContent=original;button.classList.remove("button-success","button-error","button-busy");button.disabled=false},delay)}
const profileStatus=document.createElement("div");profileStatus.id="profileSaveStatus";profileStatus.className="inline-status";profilePanel?.appendChild(profileStatus);
if($("#saveProfile")){$("#saveProfile").onclick=()=>{const data=readProfileUI(),missing=[];if(!data.birthYear)missing.push("出生年份");if(!data.height)missing.push("身高");if(!data.weight)missing.push("体重");if(!data.weeklyDays)missing.push("每周训练天数");if(!data.goal)missing.push("目标");if(!data.equipment)missing.push("训练条件");saveProfileData(data);profileInput.value=JSON.stringify(data);profileStatus.innerHTML=`<b>✓ 训练档案已保存</b><small>${missing.length?`还可补充：${esc(missing.join("、"))}`:"基础信息完整，将用于反馈和周计划"}</small>`;flashButton($("#saveProfile"),"✓ 已保存训练档案");note("训练档案保存成功，之后的反馈和计划会使用这些条件")}}
const originalHydrateProfile=hydrateProfile;hydrateProfile=function(){originalHydrateProfile();const p=loadProfile();if(Object.keys(p).some(k=>p[k]!==null&&p[k]!=="")){profileStatus.innerHTML='<b>✓ 已载入本账户训练档案</b><small>修改后请再次点击保存</small>'}};hydrateProfile();

function feedbackTextNow(){return String(currentFeedback||$("#dailyFeedback p")?.textContent||$("#modalFeedback")?.textContent||"").trim()}
let activeUtterance=null,voiceWatchdog=null,activeAudio=null,audioQueue=[],audioIndex=0;
function stopSpeaking(){clearTimeout(voiceWatchdog);if("speechSynthesis" in window)speechSynthesis.cancel();if(activeAudio){activeAudio.pause();activeAudio.removeAttribute("src");activeAudio.load();activeAudio.remove()}activeAudio=null;audioQueue=[];audioIndex=0;activeUtterance=null;[$("#playVoice"),$("#modalPlay")].forEach(b=>{if(b){b.textContent=b.id==="playVoice"?"▶ 听反馈":"▶ 播放教练反馈";b.classList.remove("is-speaking","button-error","button-busy")}})}
function wechatSpeak(text,button){text=String(text||"").replace(/\s+/g," ").trim();if(!text){note("当前还没有可播放的反馈，请先保存当天记录");flashButton(button,"暂无反馈","error");return}if(!("speechSynthesis" in window)||typeof SpeechSynthesisUtterance==="undefined"){note("当前微信内核没有提供系统朗读能力，请点击右上角用系统浏览器打开，或直接阅读文字反馈");flashButton(button,"此微信暂不支持语音","error",3500);return}stopSpeaking();const utterance=new SpeechSynthesisUtterance(text.slice(0,900)),voice=chosenVoice();activeUtterance=utterance;if(voice)utterance.voice=voice;utterance.lang="zh-CN";utterance.rate=.9;utterance.pitch=1.03;utterance.volume=1;let started=false;utterance.onstart=()=>{started=true;button.textContent="■ 停止播放";button.classList.add("is-speaking");note("正在播放今日反馈…再次点击可以停止")};utterance.onend=()=>{activeUtterance=null;button.textContent=button.id==="playVoice"?"↻ 再听一次":"↻ 再播放一次";button.classList.remove("is-speaking");note("反馈播放完毕")};utterance.onerror=e=>{activeUtterance=null;button.classList.remove("is-speaking");button.textContent="语音播放失败 · 点此重试";button.classList.add("button-error");note(`语音没有成功播放${e?.error?`（${e.error}）`:""}。请确认手机媒体音量，或用系统浏览器打开后重试`)};speechSynthesis.resume();speechSynthesis.speak(utterance);voiceWatchdog=setTimeout(()=>{if(!started&&!speechSynthesis.speaking){speechSynthesis.cancel();utterance.voice=null;speechSynthesis.resume();speechSynthesis.speak(utterance)}},900)}
function speechChunks(text,max=72){const sentences=String(text).replace(/\s+/g," ").match(/[^。！？；]+[。！？；]?/g)||[String(text)];const chunks=[];sentences.forEach(sentence=>{let rest=sentence.trim();while(rest.length>max){let cut=Math.max(rest.lastIndexOf("，",max),rest.lastIndexOf("、",max));if(cut<20)cut=max;chunks.push(rest.slice(0,cut+1));rest=rest.slice(cut+1)}if(rest)chunks.push(rest)});return chunks.filter(Boolean)}
function onlineVoiceUrl(text){return`https://fanyi.baidu.com/gettts?lan=zh&text=${encodeURIComponent(text)}&spd=4&source=web`}
async function playOnlineChunk(button){if(audioIndex>=audioQueue.length){activeAudio=null;button.textContent=button.id==="playVoice"?"↻ 再听一次":"↻ 再播放一次";button.classList.remove("is-speaking","button-busy");note("反馈播放完毕");return}const audio=document.createElement("audio");activeAudio=audio;audio.preload="auto";audio.playsInline=true;audio.setAttribute("webkit-playsinline","");audio.src=onlineVoiceUrl(audioQueue[audioIndex]);audio.onplaying=()=>{button.textContent="■ 停止播放";button.classList.remove("button-busy");button.classList.add("is-speaking");note(`正在播放今日反馈（${audioIndex+1}/${audioQueue.length}）…`)};audio.onended=()=>{audio.remove();activeAudio=null;audioIndex++;playOnlineChunk(button)};audio.onerror=()=>{audio.remove();activeAudio=null;audioQueue=[];button.classList.remove("is-speaking","button-busy");note("在线音频加载失败，正在尝试手机系统朗读…");wechatSpeak(feedbackTextNow(),button)};document.body.appendChild(audio);try{await audio.play()}catch(e){audio.onerror?.(e)}}
function onlineSpeakFeedback(text,button){text=String(text||"").trim();if(!text){note("当前还没有可播放的反馈，请先保存当天记录");return flashButton(button,"暂无反馈","error")}if(localStorage.getItem("fitness-online-voice-consent")!=="yes"){const ok=confirm("为解决微信内无法朗读的问题，需要将本次反馈文字发送给百度在线语音服务生成音频。不会发送照片、恢复码或完整训练档案。是否启用在线语音？");if(!ok){note("未启用在线语音；反馈文字仍可正常阅读");return}localStorage.setItem("fitness-online-voice-consent","yes")}stopSpeaking();audioQueue=speechChunks(text);audioIndex=0;button.textContent="正在加载语音…";button.classList.add("button-busy");button.disabled=false;playOnlineChunk(button)}
function voiceButtonClick(button){if(activeAudio||activeUtterance||("speechSynthesis" in window&&speechSynthesis.speaking)){stopSpeaking();note("已停止播放");return}onlineSpeakFeedback(feedbackTextNow(),button)}
$("#playVoice").onclick=()=>voiceButtonClick($("#playVoice"));
$("#modalPlay").onclick=()=>voiceButtonClick($("#modalPlay"));
showFeedback=function(p){currentFeedback=feedbackFor(p);$("#modalFeedback").textContent=currentFeedback;$("#feedbackModal").classList.remove("hidden");$("#modalPlay").textContent="▶ 点击播放教练反馈";note("日报已生成。微信要求你主动点击按钮后才能播放声音")};
document.addEventListener("visibilitychange",()=>{if(document.hidden)stopSpeaking()});

$("#showDate").onclick=e=>{e.preventDefault();const d=$("#historyDate").value;if(!d){note("请先选择要查看的日期");return flashButton($("#showDate"),"请先选日期","error")}const count=allRows.filter(x=>x.payload?.logDate===d).length;filterDate(d);flashButton($("#showDate"),count?`✓ 找到 ${count} 条`:`${d} 无记录`,count?"success":"error");note(count?`已显示 ${d} 的 ${count} 条记录`:`${d} 暂无训练记录`)};
$("#showAll").onclick=e=>{e.preventDefault();$("#historyDate").value="";document.querySelectorAll(".date-chip").forEach(b=>b.classList.remove("selected"));renderLogs(allRows);flashButton($("#showAll"),`✓ 已显示 ${allRows.length} 条`);note(`已显示本账户全部 ${allRows.length} 条记录`)};
$("#refreshReport").onclick=async()=>{const btn=$("#refreshReport");flashButton(btn,"正在重新分析…","busy");try{await ensureRows(true);renderCoach(allRows);flashButton(btn,"✓ 分析已更新");note("训练计划和分析报告已根据最新记录更新")}catch(e){flashButton(btn,"更新失败","error");note(e.message||"分析更新失败")}};
document.querySelectorAll(".module-save").forEach(btn=>btn.addEventListener("click",()=>flashButton(btn,btn.textContent.startsWith("✓")?btn.textContent:`✓ ${moduleNames[btn.closest(".record-module")?.dataset.module]||"本项"}已保存`)));

$("#date")?.addEventListener("change",()=>{loadMealResults();syncEnergyFields()});
$("#createAccount")?.addEventListener("click",()=>setTimeout(loadMealResults,0));$("#restoreButton")?.addEventListener("click",()=>setTimeout(loadMealResults,0));
const nutritionValidate=validateEntry;validateEntry=function(p){const base=nutritionValidate(p);if(base)return base;for(const [name,max,label] of [["activeCalories",6000,"手表活动消耗"],["trainingCalories",4000,"训练消耗"],["proteinGrams",500,"蛋白质"]]){if(p[name]!=null&&p[name]!==""&&(!Number.isFinite(Number(p[name]))||Number(p[name])<0||Number(p[name])>max))return`${label}应填写 0–${max} 之间的数值`}return""};
const nutritionFeedback=feedbackFor;feedbackFor=function(p){const base=nutritionFeedback(p),m=energyMetrics(p);if(!m.complete)return`${base}\n\n能量分析：训练档案中的出生年份、身高和体重补全后，才能计算基础代谢和全天消耗。`;let meals={};try{meals=typeof p.mealsJson==="string"?JSON.parse(p.mealsJson):p.mealsJson||{}}catch{}const mealCount=Object.values(meals).filter(x=>x?.confirmed).length;let energy="";if(mealCount<3)energy=`今天只确认了 ${mealCount} 个餐次，摄入数据还不完整，暂不依据热量差调整训练或饮食。`;else if(m.balance<-700)energy=`全天约摄入 ${m.intake} kcal、消耗 ${m.expenditure} kcal，差值约 ${m.balance} kcal，缺口偏大。连续这样会影响力量表现和睡眠恢复；下一餐优先补主食与优质蛋白，不用靠挨饿减脂。`;else if(m.balance>700)energy=`全天约摄入 ${m.intake} kcal、消耗 ${m.expenditure} kcal，盈余约 +${m.balance} kcal。单日不用紧张，但若腰围连续两周上升，先从酒精、油脂和零食中小幅减少，不削减训练前后的正餐。`;else energy=`全天约摄入 ${m.intake} kcal、消耗 ${m.expenditure} kcal，热量差约 ${m.balance>0?"+":""}${m.balance} kcal，处在可观察范围。更重要的是看连续 7–14 天体重、腰围和训练表现，而不是追逐单日数字。`;const protein=m.protein>=m.proteinMin?`蛋白质约 ${m.protein} g，达到当前参考下限 ${m.proteinMin} g。`:`蛋白质约 ${m.protein} g，距离参考下限 ${m.proteinMin} g 还差约 ${Math.max(0,Math.round(m.proteinMin-m.protein))} g；可分到下一餐补充，而不是临睡前一次硬塞。`;return`${base}\n\n能量与营养：${energy}${protein}照片识别存在份量误差，所有结果都以你确认后的数值为准。`};
const nutritionLogCard=logCard;logCard=function(x){let html=nutritionLogCard(x),p=x.payload||{},m=energyMetrics(p);if(!m.complete||!p.estimatedCalories)return html;const nutrition=`<div class="stats"><span>摄入<br><b>${Math.round(Number(p.estimatedCalories)||0)} kcal</b></span><span>总消耗<br><b>${Math.round(Number(p.totalExpenditure)||m.expenditure)} kcal</b></span><span>热量差<br><b>${Number(p.calorieBalance)>0?"+":""}${Math.round(Number(p.calorieBalance)||m.balance||0)}</b></span><span>蛋白质<br><b>${Math.round(Number(p.proteinGrams)||0)} g</b></span></div>`;return html.replace("</article>",nutrition+"</article>")};
const nutritionCoach=renderCoach;renderCoach=function(rows){nutritionCoach(rows);const recent=[...rows].sort((a,b)=>String(a.payload?.logDate||"").localeCompare(String(b.payload?.logDate||""))).slice(-7).map(x=>x.payload||{}).filter(x=>Number(x.estimatedCalories)>0&&Number(x.totalExpenditure)>0);if(!recent.length)return;const avgIntake=Math.round(recent.reduce((s,x)=>s+Number(x.estimatedCalories),0)/recent.length),avgBurn=Math.round(recent.reduce((s,x)=>s+Number(x.totalExpenditure),0)/recent.length),avgBalance=Math.round(recent.reduce((s,x)=>s+Number(x.calorieBalance||Number(x.estimatedCalories)-Number(x.totalExpenditure)),0)/recent.length),proteinDays=recent.filter(x=>Number(x.proteinGrams)>=Number(x.proteinTargetMin||999)).length,max=Math.max(...recent.flatMap(x=>[Number(x.estimatedCalories),Number(x.totalExpenditure)]),1);const card=document.createElement("section");card.className="report-card nutrition-report";card.innerHTML=`<h3>近 ${recent.length} 日能量与营养</h3><div class="metric-grid">${metric("平均摄入",avgIntake,"kcal","")}${metric("平均消耗",avgBurn,"kcal","")}${metric("平均热量差",avgBalance,"kcal",Math.abs(avgBalance)<=500?"可观察":"需调整")}${metric("蛋白达标",proteinDays,"天",`共${recent.length}天`)}</div><div class="nutrition-bars">${recent.map(p=>`<div><small>${shortDate(p.logDate||"")}</small><i style="height:${Math.max(8,Math.round(Number(p.estimatedCalories)/max*88))}px" title="摄入 ${p.estimatedCalories}"></i><i class="burn" style="height:${Math.max(8,Math.round(Number(p.totalExpenditure)/max*88))}px" title="消耗 ${p.totalExpenditure}"></i></div>`).join("")}</div><p>粉色＝摄入，蓝色＝总消耗。照片估算用于趋势管理，不替代称重或营养医学评估。</p>`;$("#coachReport")?.prepend(card)};
