const SUPABASE_URL="https://cjayajcjmpjjczwueyur.supabase.co";
const SUPABASE_KEY="sb_publishable_gID5KWmnvlNS3acHBkyETg_W6ACSKdB";
const extraStyle=document.createElement("link");extraStyle.rel="stylesheet";extraStyle.href="./style-extra.css?v=20260823-5";document.head.appendChild(extraStyle);
const chartStyle=document.createElement("link");chartStyle.rel="stylesheet";chartStyle.href="./style-charts.css?v=20260823-3";document.head.appendChild(chartStyle);
const $=s=>document.querySelector(s),urlKey=new URLSearchParams(location.search).get("key")||"";let key=urlKey||localStorage.getItem("fitness-key")||"";
let allRows=[];if(urlKey){localStorage.setItem("fitness-key",urlKey);history.replaceState({},document.title,location.pathname+location.hash)}const today=()=>new Date().toLocaleDateString("en-CA");$("#date").value=today();
function syncAccountUI(){const bound=Boolean(key);$("#accountButton").textContent=bound?"● 已免登录绑定":"○ 恢复账户";$("#accountButton").classList.toggle("unbound",!bound);$("#boundAccount").classList.toggle("hidden",!bound);$("#restoreAccount").classList.toggle("hidden",bound);if(!bound)$("#accountModal").classList.remove("hidden")}
$("#accountButton").onclick=()=>{$("#accountModal").classList.remove("hidden");syncAccountUI()};$("#closeAccount").onclick=()=>$("#accountModal").classList.add("hidden");
$("#copyRecovery").onclick=async()=>{try{await navigator.clipboard.writeText(key);note("恢复码已复制，请只保存到你自己的备忘录中")}catch{prompt("请复制并妥善保存恢复码",key)}};
$("#restoreButton").onclick=async()=>{const value=$("#recoveryInput").value.trim();if(!/^[A-Za-z0-9_-]{20,}$/.test(value))return note("恢复码格式不正确");try{await rpc("list_fitness_logs",{p_key:value});key=value;localStorage.setItem("fitness-key",key);allRows=[];syncAccountUI();$("#accountModal").classList.add("hidden");note("账户恢复成功，此微信以后将自动进入");await ensureRows(true)}catch{note("恢复码无效，请检查后重试")}};
syncAccountUI();
$("#mascot").style.backgroundImage="url('./fitness-mascot-v1.webp')";
document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=async()=>{document.querySelectorAll("[data-tab]").forEach(x=>x.classList.remove("active"));b.classList.add("active");["form","history","coach"].forEach(t=>$("#"+t+"View").classList.toggle("hidden",b.dataset.tab!==t));if(b.dataset.tab!=="form")await ensureRows();if(b.dataset.tab==="history")renderHistory(allRows);if(b.dataset.tab==="coach")renderCoach(allRows)});
const note=t=>{$("#notice").textContent=t;$("#notice").classList.remove("hidden");scrollTo({top:0,behavior:"smooth"})};
$("#files").onchange=e=>$("#fileText").textContent=`已选择 ${Math.min(e.target.files.length,6)} 张截图`;
async function rpc(name,body){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:"POST",headers:{"Content-Type":"application/json","apikey":SUPABASE_KEY},body:JSON.stringify(body)});const text=await r.text();let out=null;try{out=text?JSON.parse(text):null}catch{out=text}if(!r.ok)throw Error(out?.message||out?.error||`请求失败（${r.status}）`);return out}
async function compress(file){if(!file.type.startsWith("image/"))throw Error(`${file.name} 不是图片`);const bitmap=await createImageBitmap(file),max=1280,scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement("canvas");canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext("2d").drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close?.();let quality=.76,data=canvas.toDataURL("image/jpeg",quality);while(data.length>320000&&quality>.42){quality-=.08;data=canvas.toDataURL("image/jpeg",quality)}if(data.length>430000)throw Error(`${file.name} 压缩后仍过大，请裁剪后上传`);return{name:file.name,mime_type:"image/jpeg",data}}
$("#logForm").onsubmit=async e=>{e.preventDefault();if(!key)return note("请使用专属链接进入");const btn=$("#save");btn.disabled=true;note("正在压缩截图并保存…");try{const f=new FormData(e.target),files=[...$("#files").files].slice(0,6),images=[];for(const file of files)images.push(await compress(file));const data=Object.fromEntries(f.entries());["sleepHours","wakeCount","energy","restingHr","duration","avgHr","maxHr","completion"].forEach(n=>data[n]=data[n]===""?null:Number(data[n]));await rpc("save_fitness_log",{p_key:key,p_payload:data,p_images:images});allRows=[];e.target.reset();$("#date").value=today();$("#fileText").textContent="选择训练 / 睡眠 / 饮食截图";note("已保存。今天的反馈已经生成。");showFeedback(data);await ensureRows(true)}catch(err){note(err.message||"保存失败")}finally{btn.disabled=false}};
async function ensureRows(force=false){if(!key){note("请使用专属链接进入");return[]}if(allRows.length&&!force)return allRows;try{allRows=await rpc("list_fitness_logs",{p_key:key});updateMascot(allRows);return allRows}catch(err){note(err.message||"读取失败");return[]}}
function renderHistory(rows){const dates=[...new Set(rows.map(x=>x.payload?.logDate).filter(Boolean))].sort().reverse();$("#historyCount").textContent=`${rows.length} 条`;$("#dateStrip").innerHTML=dates.slice(0,12).map((d,i)=>`<button data-date="${esc(d)}" class="date-chip${i===0?' selected':''}">${shortDate(d)}</button>`).join("");$("#dateStrip").querySelectorAll("[data-date]").forEach(b=>b.onclick=()=>{$("#historyDate").value=b.dataset.date;filterDate(b.dataset.date)});renderDailyFeedback(rows[0]?.payload||null);renderLogs(rows)}
function filterDate(date){document.querySelectorAll(".date-chip").forEach(b=>b.classList.toggle("selected",b.dataset.date===date));renderLogs(allRows.filter(x=>x.payload?.logDate===date),date)}
$("#showDate").onclick=e=>{e.preventDefault();const d=$("#historyDate").value;if(d)filterDate(d)};$("#showAll").onclick=e=>{e.preventDefault();$("#historyDate").value="";document.querySelectorAll(".date-chip").forEach(b=>b.classList.remove("selected"));renderLogs(allRows)};
function renderLogs(rows,date=""){$("#logs").innerHTML=rows.length?rows.map(logCard).join(""):`<div class="empty">${date?esc(date)+" 暂无记录":"还没有记录"}</div>`}
function logCard(x){const p=x.payload||{},imgs=x.images||[];return `<article class="log"><div class="log-top"><div><small>${esc(p.logDate||"")}</small><h3>${esc(p.sessionType||"日常反馈")}</h3></div><span class="status-dot">已记录</span></div><div class="stats"><span>睡眠<br><b>${p.sleepHours??"—"}h</b></span><span>时长<br><b>${p.duration??"—"}min</b></span><span>平均心率<br><b>${p.avgHr??"—"}</b></span><span>精力<br><b>${p.energy??"—"}/5</b></span></div>${block("训练",p.exercises)}${block("饮食",p.meals)}${block("身体反馈",p.symptoms)}${block("备注",p.notes)}${imgs.length?`<div class="gallery">${imgs.map(i=>`<a target="_blank" href="${i.data}"><img loading="lazy" src="${i.data}" alt="反馈截图"></a>`).join("")}</div>`:""}</article>`}
function feedbackFor(p){if(!p)return"程楠，今天还没看到你的记录呢。别给自己太大压力，哪怕只记下睡眠和身体状态，也算把今天接住了。";const name="程楠",session=p.sessionType||"训练",opening=p.duration>0?`${name}，我刚认真看完你今天的记录。${p.duration} 分钟的${session}，你确实做下来了。`:`${name}，我看完了。今天虽然没有正式训练，但你愿意把真实状态留下来，这很重要。`;let praise="";if(p.completion>=85)praise=`完成度 ${p.completion}%，挺漂亮的。不是嘴上说想改变，是你真的在一点点往前拱。`;else if(p.completion>=60)praise=`完成度 ${p.completion}%，不用嫌它不够满。能稳定做下去，比偶尔拼一次狠的更值钱。`;else if(p.duration>0)praise="今天不用追求满分。先把动作做稳，把呼吸守住，这次训练就有价值。";let focus="";if(hasSymptom(p.symptoms))focus=`但我最在意的是你写的“${p.symptoms}”。下一次先降重量、减一到两组，别硬扛；如果是视力变化、眼痛、胸闷、头晕或异常心悸，就先停下来去看医生。`;else if(p.sleepHours&&p.sleepHours<6.5)focus=`不过你只睡了 ${p.sleepHours} 小时。今晚别想着靠多练补回来，真正该补的是睡眠。下一次训练保留三到四次余力，做完还有劲儿，才是对的。`;else if(p.wakeCount>=2)focus=`夜里醒了 ${p.wakeCount} 次，这说明身体恢复得不算完整。下一次别加训练量，动作之间多歇一会儿，下午也尽量早点结束。`;else if(p.maxHr>=150)focus=`最高心率到了 ${p.maxHr}。单看数字不一定有问题，但你要记得当时有没有胸闷、头晕或心慌；有任何不舒服，就不要继续顶。`;else focus="今天的数据里没看到明显的危险信号。继续记住三件事：不憋气，不震动，不练到力竭。动作慢一点，反而更适合你。";const close=p.duration>0?"好了，今天这次算数。去吃一顿有蛋白质的饭，晚上早点睡。明天不用证明什么，我们接着来。":"今天就先把恢复做好。喝水分次喝，晚上早点躺下。等身体准备好了，我们再稳稳地练。";return[opening,praise,focus,close].filter(Boolean).join("\n\n")}
let currentFeedback="";function renderDailyFeedback(p){currentFeedback=feedbackFor(p);$("#dailyFeedback").innerHTML=`<div class="voice-orb">♪</div><div><b>${p?esc(p.logDate||"最近一次")+" · "+esc(p.sessionType||"反馈"):"等待第一次记录"}</b><p>${esc(currentFeedback)}</p></div>`}
function showFeedback(p){currentFeedback=feedbackFor(p);$("#modalFeedback").textContent=currentFeedback;$("#feedbackModal").classList.remove("hidden");speakFeedback(currentFeedback)}
let cloudAudio=null;function systemSpeakFeedback(text){if(!("speechSynthesis" in window))return note("当前微信浏览器不支持语音播放，请阅读文字反馈");speechSynthesis.cancel();const voices=speechSynthesis.getVoices(),female=voices.find(v=>/Xiaoxiao|Xiaoyi|Ting-Ting|Sinji|Meijia|female|女声/i.test(v.name)&&/^zh/i.test(v.lang))||voices.find(v=>/^zh-CN/i.test(v.lang))||voices.find(v=>/^zh/i.test(v.lang)),parts=String(text).split(/\n{2,}|(?<=[。！？])\s*/).map(x=>x.trim()).filter(Boolean);let i=0;const play=()=>{if(i>=parts.length)return;const u=new SpeechSynthesisUtterance(parts[i]);u.voice=female||null;u.lang="zh-CN";u.rate=i===0?.86:.89;u.pitch=i===0?1.04:1.01;u.volume=1;u.onend=()=>{i++;setTimeout(play,i===1?260:150)};u.onerror=()=>{i++;play()};speechSynthesis.speak(u)};play()}
async function speakFeedback(text=currentFeedback){if(!text)return;const buttons=[$("#playVoice"),$("#modalPlay")].filter(Boolean),labels=buttons.map(b=>b.textContent);buttons.forEach(b=>{b.disabled=true;b.textContent="正在生成甜美女声…"});try{cloudAudio?.pause();const response=await fetch(`${SUPABASE_URL}/functions/v1/tencent-tts`,{method:"POST",headers:{"Content-Type":"application/json","apikey":SUPABASE_KEY},body:JSON.stringify({text,accountKey:key})});if(!response.ok){const detail=await response.json().catch(()=>({}));throw Error(detail.error||"云端语音暂不可用")}const blob=await response.blob();cloudAudio=new Audio(URL.createObjectURL(blob));cloudAudio.preload="auto";await cloudAudio.play()}catch(error){note(`${error.message||"云端语音暂不可用"}，已切换手机女声`);systemSpeakFeedback(text)}finally{buttons.forEach((b,i)=>{b.disabled=false;b.textContent=labels[i]})}}
$("#playVoice").onclick=()=>speakFeedback();$("#modalPlay").onclick=()=>speakFeedback();$("#closeFeedback").onclick=()=>$("#feedbackModal").classList.add("hidden");$("#goFeedback").onclick=()=>{$("#feedbackModal").classList.add("hidden");document.querySelector('[data-tab="history"]').click()};
function updateMascot(rows){const dates=[...new Set(rows.map(x=>x.payload?.logDate).filter(Boolean))],set=new Set(dates);let streak=0,d=new Date();for(let i=0;i<60;i++){const ds=d.toLocaleDateString("en-CA");if(set.has(ds))streak++;else if(i>0)break;d.setDate(d.getDate()-1)}const total28=dates.filter(x=>(Date.now()-new Date(x+"T12:00:00").getTime())/864e5<=28).length,stage=total28>=16?3:total28>=9?2:total28>=4?1:0,m=$("#mascot");m.className=`mascot stage-${stage} motion-${new Date().getDate()%3}`;$("#streakBadge").textContent=`连续 ${streak} 天`;const titles=["今天，从第一步开始","肚子在退，状态在来","力量已经看得见","你正在成为自己的高光"];$("#mascotTitle").textContent=titles[stage];$("#mascotSub").textContent=`近28天已记录 ${total28} 天 · 再坚持就会继续进化`}
$("#refreshReport").onclick=async()=>{await ensureRows(true);renderCoach(allRows)};
function renderCoach(rows){$("#coachLoading").classList.add("hidden");$("#coachReport").classList.remove("hidden");if(!rows.length){$("#coachReport").innerHTML='<div class="empty">至少保存 1 条反馈后生成第一份教练报告。</div>';return}const recent=[...rows].sort((a,b)=>String(a.payload?.logDate||"").localeCompare(String(b.payload?.logDate||""))).slice(-14),ps=recent.map(x=>x.payload||{}),avgSleep=avg(ps,"sleepHours"),avgWake=avg(ps,"wakeCount"),avgEnergy=avg(ps,"energy"),avgRest=avg(ps,"restingHr"),avgComp=avg(ps,"completion"),sessions=ps.filter(p=>p.duration>0).length,minutes=sum(ps,"duration"),last=ps.at(-1)||{};let score=70;if(avgSleep!==null)score+=clamp((avgSleep-6.5)*10,-18,12);if(avgWake!==null)score+=clamp((1.5-avgWake)*5,-14,7);if(avgEnergy!==null)score+=clamp((avgEnergy-3)*7,-14,14);if(avgComp!==null)score+=clamp((avgComp-75)/4,-8,6);score=Math.round(clamp(score,30,96));const warnings=[];if(last.maxHr>=150)warnings.push(`最近一次最高心率 ${last.maxHr}：记录当时感受。若伴胸闷、头晕、异常心悸应停止训练并就医。`);if(hasSymptom(last.symptoms))warnings.push(`最近一次记录了身体异常：“${esc(last.symptoms)}”。下一次先降量，并根据症状决定是否就医。`);if(avgSleep!==null&&avgSleep<7)warnings.push(`近 ${recent.length} 次平均睡眠 ${fmt(avgSleep)} 小时，低于增肌恢复所需的优先目标。`);const advice=buildAdvice({score,avgSleep,avgWake,sessions,minutes});$("#coachReport").innerHTML=`<section class="score-card"><div><p>当前恢复准备度</p><strong>${score}</strong><span>/100</span></div><div class="score-copy"><b>${score>=80?'状态良好':score>=65?'可以训练，控制强度':'优先恢复，建议降量'}</b><small>依据最近 ${recent.length} 条记录动态计算</small></div></section><section class="metric-grid">${metric("平均睡眠",avgSleep,"小时",trend(ps,"sleepHours"))}${metric("平均夜醒",avgWake,"次",avgWake!==null&&avgWake>2?"需改善":"稳定")}${metric("晨间心率",avgRest,"bpm",trend(ps,"restingHr"))}${metric("计划完成",avgComp,"%",avgComp!==null&&avgComp>=80?"良好":"观察")}</section>${trendChart(ps)}<section class="report-card"><h3>本期判断</h3><ul>${advice.summary.map(x=>`<li>${x}</li>`).join("")}</ul></section><section class="report-card action"><h3>下一次训练处方</h3><ol>${advice.next.map(x=>`<li>${x}</li>`).join("")}</ol></section><section class="report-card safety"><h3>你的固定安全边界</h3><ul><li>双眼人工晶体双点悬挂：不跑跳、不冲击、不剧烈震动，器械起落保持平稳。</li><li>力量训练全程呼气发力，不憋气；保留 2–4 次余力（RIR 2–4），不做力竭组和极限重量测试。</li><li>快走建议心率 105–125 次/分，30–45 分钟；能完整说短句，避免冲刺。</li></ul></section>${warnings.length?`<section class="report-card warning"><h3>本期风险提示</h3><ul>${warnings.map(x=>`<li>${x}</li>`).join("")}</ul></section>`:""}<p class="generated">生成时间：${new Date().toLocaleString("zh-CN",{hour12:false})} · 数据范围：最近 ${recent.length} 条</p>`}
function buildAdvice(s){const summary=[],next=[];if(s.avgSleep!==null)summary.push(s.avgSleep>=7?`平均睡眠 ${fmt(s.avgSleep)} 小时，时长基本达标；继续重点观察夜醒。`:`平均睡眠仅 ${fmt(s.avgSleep)} 小时，当前增肌瓶颈更可能是恢复而不是训练量。`);else summary.push("睡眠数据不足，连续记录 7 天后才能判断恢复趋势。");if(s.avgWake!==null&&s.avgWake>=2)summary.push(`平均夜醒 ${fmt(s.avgWake)} 次，睡眠连续性仍是首要改善项。`);summary.push(s.sessions>=4?`记录期内完成 ${s.sessions} 次训练、${Math.round(s.minutes)} 分钟，频率足够，暂不增加训练日。`:`记录期内有 ${s.sessions} 次有效训练，先建立稳定的周一、二、四、五节奏。`);if(s.score<65)next.push("把原计划总组数减少约 25%，所有动作保留 3–4 次余力。","取消额外有氧；训练后用 10–15 分钟轻松步行收尾。");else next.push("按原计划训练，但每个动作只在动作稳定、无憋气时增加次数或小幅加重。","复合动作 RIR 3，孤立动作 RIR 2–3；组间休息 90–150 秒。");next.push("下午训练尽量在睡前 4 小时结束；训练后补充含蛋白质的一餐并正常分次补水。","若安排快走：周三或周六 30–45 分钟，心率 105–125 次/分，不追求距离和步数纪录。");return{summary,next}}
function trendChart(ps){const values=ps.map(p=>Number(p.sleepHours)||0),max=Math.max(8,...values);return `<section class="trend-card"><div class="trend-title"><h3>睡眠趋势</h3><small>最近 ${values.length} 次</small></div><div class="bars">${values.map((v,i)=>`<div class="bar-wrap" title="${esc(ps[i].logDate||'')} ${v||'—'}h"><i style="height:${v?Math.max(12,v/max*100):5}%"></i><small>${v||'—'}</small></div>`).join("")}</div></section>`}
function metric(name,value,unit,status){return `<div class="metric"><small>${name}</small><b>${value===null?'—':fmt(value)}<em>${value===null?'':unit}</em></b><span>${status||'记录中'}</span></div>`}
function avg(ps,k){const a=ps.map(p=>Number(p[k])).filter(Number.isFinite);return a.length?a.reduce((x,y)=>x+y,0)/a.length:null}function sum(ps,k){return ps.reduce((n,p)=>n+(Number(p[k])||0),0)}function trend(ps,k){const a=ps.map(p=>Number(p[k])).filter(Number.isFinite);if(a.length<4)return"数据积累中";const h=Math.floor(a.length/2),d=avgNums(a.slice(h))-avgNums(a.slice(0,h));if(Math.abs(d)<.5)return"基本稳定";return d>0?"近期上升":"近期下降"}function avgNums(a){return a.reduce((x,y)=>x+y,0)/a.length}function hasSymptom(s){return s&&!["无","没有","正常","暂无"].includes(String(s).trim())}function clamp(n,a,b){return Math.max(a,Math.min(b,n))}function fmt(n){return n===null?"—":Number(n).toFixed(1).replace(".0","")}function shortDate(d){const[,m,day]=d.split("-");return `${Number(m)}月${Number(day)}日`}function esc(s){return String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}function block(n,v){return v?`<p class="detail"><small>${n}</small><br>${esc(v)}</p>`:""}
function appendMissedPlan(rows){const now=new Date(),y=new Date(now);y.setDate(now.getDate()-1);const day=y.getDay(),map={1:"上肢 A",2:"下肢 A",4:"上肢 B",5:"下肢 B"},missed=map[day];if(!missed)return;const ymd=y.toLocaleDateString("en-CA"),done=rows.some(x=>x.payload?.logDate===ymd&&Number(x.payload?.duration)>0);if(done)return;const box=document.createElement("section");box.className="report-card rescue";box.innerHTML=`<h3>漏训补救 · ${esc(missed)}</h3><p>检测到昨天是计划训练日，但没有有效训练记录。今天不要把两天训练硬塞在一起。</p><ol><li>若恢复评分 ≥65：安排 30–40 分钟缩短版，每个动作 2 组、RIR 3，不做力竭。</li><li>若今天本来也是训练日：优先完成今天计划，把漏训移动到周三或周六；两次力量训练至少间隔 24 小时。</li><li>若睡眠不足 6 小时、夜醒明显或有身体异常：本次不补，做 20–30 分钟轻松快走和活动度练习。</li></ol>`;$("#coachReport").prepend(box)}
const baseRenderCoach=renderCoach;renderCoach=function(rows){baseRenderCoach(rows);appendMissedPlan(rows)};
trendChart=function(ps){const series=[{name:"睡眠",key:"sleepHours",unit:"h",color:"sleep"},{name:"最高心率",key:"maxHr",unit:"",color:"heart"},{name:"完成度",key:"completion",unit:"%",color:"done"}];return `<section class="trend-card"><div class="trend-title"><h3>近期开启趋势</h3><small>最近 ${ps.length} 次记录</small></div><div class="chart-stack">${series.map(s=>{const vals=ps.map(p=>Number(p[s.key])||0),max=Math.max(1,...vals);return `<div class="chart-row"><b>${s.name}</b><div class="mini-bars ${s.color}">${vals.map((v,i)=>`<i style="height:${v?Math.max(8,v/max*100):4}%" title="${esc(ps[i].logDate||'')} ${v||'—'}${s.unit}"></i>`).join("")}</div><span>${vals.at(-1)||'—'}${vals.at(-1)?s.unit:''}</span></div>`}).join("")}</div></section>`};
updateMascot=function(rows){const dates=[...new Set(rows.map(x=>x.payload?.logDate).filter(Boolean))],set=new Set(dates),trainingDays=new Set([1,2,4,5]);let streak=0,d=new Date();for(let i=0;i<80;i++){if(trainingDays.has(d.getDay())){const ds=d.toLocaleDateString("en-CA");if(set.has(ds))streak++;else if(ds!==today())break}d.setDate(d.getDate()-1)}const total28=dates.filter(x=>(Date.now()-new Date(x+"T12:00:00").getTime())/864e5<=28).length,stage=total28>=16?3:total28>=9?2:total28>=4?1:0,m=$("#mascot");m.className=`mascot stage-${stage} motion-${new Date().getDate()%3}`;$("#streakBadge").textContent=`训练日连签 ${streak}`;const titles=["今天，从第一步开始","肚子在退，状态在来","力量已经看得见","你正在成为自己的高光"];$("#mascotTitle").textContent=titles[stage];$("#mascotSub").textContent=`近28天已记录 ${total28} 天 · 休息日不会打断连签`};
ensureRows();
