const SUPABASE_URL="https://cjayajcjmpjjczwueyur.supabase.co";
const SUPABASE_KEY="sb_publishable_gID5KWmnvlNS3acHBkyETg_W6ACSKdB";
const $=s=>document.querySelector(s);
const key=new URLSearchParams(location.search).get("key")||localStorage.getItem("fitness-key")||"";
if(key)localStorage.setItem("fitness-key",key);
$("#date").value=new Date().toLocaleDateString("en-CA");
document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-tab]").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#formView").classList.toggle("hidden",b.dataset.tab!=="form");$("#historyView").classList.toggle("hidden",b.dataset.tab!=="history");if(b.dataset.tab==="history")load()});
const note=t=>{$("#notice").textContent=t;$("#notice").classList.remove("hidden")};
$("#files").onchange=e=>$("#fileText").textContent=`已选择 ${Math.min(e.target.files.length,6)} 张截图`;
async function rpc(name,body){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:"POST",headers:{"Content-Type":"application/json","apikey":SUPABASE_KEY,"Authorization":`Bearer ${SUPABASE_KEY}`},body:JSON.stringify(body)});const text=await r.text();let out=null;try{out=text?JSON.parse(text):null}catch{out=text}if(!r.ok)throw Error(out?.message||out?.error||`请求失败（${r.status}）`);return out}
async function compress(file){if(!file.type.startsWith("image/"))throw Error(`${file.name} 不是图片`);const bitmap=await createImageBitmap(file),max=1280,scale=Math.min(1,max/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement("canvas");canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext("2d").drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close?.();let quality=.76,data=canvas.toDataURL("image/jpeg",quality);while(data.length>320000&&quality>.42){quality-=.08;data=canvas.toDataURL("image/jpeg",quality)}if(data.length>430000)throw Error(`${file.name} 压缩后仍过大，请裁剪后上传`);return{name:file.name,mime_type:"image/jpeg",data}}
$("#logForm").onsubmit=async e=>{e.preventDefault();if(!key)return note("请使用专属链接进入");const btn=$("#save");btn.disabled=true;note("正在压缩截图并保存…");try{const f=new FormData(e.target),files=[...$("#files").files].slice(0,6),images=[];for(const file of files)images.push(await compress(file));const data=Object.fromEntries(f.entries());delete data.files;["sleepHours","wakeCount","energy","restingHr","duration","avgHr","maxHr","completion"].forEach(n=>data[n]=data[n]===""?null:Number(data[n]));await rpc("save_fitness_log",{p_key:key,p_payload:data,p_images:images});e.target.reset();$("#date").value=new Date().toLocaleDateString("en-CA");$("#fileText").textContent="选择训练 / 睡眠 / 饮食截图";note("已保存，今天的反馈已经进入记录。")}catch(err){note(err.message||"保存失败")}finally{btn.disabled=false}};
async function load(){if(!key)return note("请使用专属链接进入");$("#logs").innerHTML="正在读取…";try{const rows=await rpc("list_fitness_logs",{p_key:key});$("#logs").innerHTML=rows.length?rows.map(x=>{const p=x.payload||{},imgs=x.images||[];return `<article class="log"><small>${esc(p.logDate||"")}</small><h3>${esc(p.sessionType||"日常反馈")}</h3><div class="stats"><span>睡眠<br><b>${p.sleepHours??"—"}h</b></span><span>时长<br><b>${p.duration??"—"}min</b></span><span>平均心率<br><b>${p.avgHr??"—"}</b></span><span>精力<br><b>${p.energy??"—"}/5</b></span></div>${block("训练",p.exercises)}${block("饮食",p.meals)}${block("身体反馈",p.symptoms)}${block("备注",p.notes)}${imgs.length?`<div class="gallery">${imgs.map(i=>`<a target="_blank" href="${i.data}"><img loading="lazy" src="${i.data}" alt="反馈截图"></a>`).join("")}</div>`:""}</article>`}).join(""):"还没有记录。"}catch(err){$("#logs").textContent=err.message||"读取失败"}}
function esc(s){return String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function block(n,v){return v?`<p class="detail"><small>${n}</small><br>${esc(v)}</p>`:""}
